/**
 * Ventlore v0.3 Enums
 * Theo Ventlore_Logic_ID_DB_v0_3.pdf & STATE_MACHINES.md
 */

export enum RoleType {
  MEMBER = 'MEMBER',
  EXPERT = 'EXPERT',
  OPERATOR = 'OPERATOR',
  TREASURY = 'TREASURY',
  ADMIN = 'ADMIN'
}

export enum PlaceStatus {
  CANDIDATE = 'CANDIDATE',
  ACTIVE = 'ACTIVE',
  MERGED = 'MERGED',
  ARCHIVED = 'ARCHIVED',
  REJECTED = 'REJECTED'
}

export enum PostVisibility {
  REVIEW_ONLY = 'REVIEW_ONLY',
  PUBLISHED = 'PUBLISHED',
  HIDDEN = 'HIDDEN'
}

export enum ContributionType {
  DISCOVERY = 'DISCOVERY',
  GUIDE = 'GUIDE',
  EXPERIENCE = 'EXPERIENCE'
}

export enum AccessTier {
  PUBLIC = 'PUBLIC',
  VIP = 'VIP'
}

export enum VerificationStatus {
  UNVERIFIED = 'UNVERIFIED',
  IN_REVIEW = 'IN_REVIEW',
  VERIFIED = 'VERIFIED',
  NEEDS_CHANGES = 'NEEDS_CHANGES',
  INCONCLUSIVE = 'INCONCLUSIVE',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  SUSPENDED = 'SUSPENDED'
}

export enum ReviewDecisionOutcome {
  APPROVED = 'APPROVED',
  CHANGES_REQUESTED = 'CHANGES_REQUESTED',
  INCONCLUSIVE = 'INCONCLUSIVE',
  REJECTED = 'REJECTED'
}

export enum TaskType {
  NEW_PLACE_REVIEW = 'NEW_PLACE_REVIEW',
  EXISTING_PLACE_POST_REVIEW = 'EXISTING_PLACE_POST_REVIEW'
}

export enum TaskWorkStatus {
  OFFERED = 'OFFERED',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
  OFFER_EXPIRED = 'OFFER_EXPIRED',
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  NEEDS_MORE = 'NEEDS_MORE',
  ACCEPTED_WORK = 'ACCEPTED_WORK',
  REJECTED_WORK = 'REJECTED_WORK',
  CANCELLED = 'CANCELLED'
}

export enum PayableStatus {
  OPEN = 'OPEN',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  UNKNOWN = 'UNKNOWN',
  PAID = 'PAID',
  CANCELLED = 'CANCELLED'
}

export enum TipRouteStatus {
  AWAITING_CONSENT = 'AWAITING_CONSENT',
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  EXPIRED = 'EXPIRED',
  REVOKED = 'REVOKED'
}

export enum GrantStatus {
  ELIGIBLE = 'ELIGIBLE',
  AUTHORIZED = 'AUTHORIZED',
  PENDING = 'PENDING',
  ISSUED = 'ISSUED',
  REVOKED = 'REVOKED'
}

export enum DonationKind {
  PROJECT = 'PROJECT',
  POST_TIP = 'POST_TIP'
}

export enum TreasuryFundingSource {
  OWNER_FUNDING = 'OWNER_FUNDING',
  PROJECT_DONATION = 'PROJECT_DONATION',
  POST_TIP_SHARE = 'POST_TIP_SHARE',
  VIP_REVENUE = 'VIP_REVENUE',
  TASK_PAYOUT = 'TASK_PAYOUT',
  REFUND = 'REFUND'
}

export enum TxAttemptStatus {
  SUBMITTED = 'SUBMITTED',
  OBSERVED = 'OBSERVED',
  FINALIZED = 'FINALIZED',
  REJECTED = 'REJECTED',
  REVERTED = 'REVERTED',
  UNKNOWN = 'UNKNOWN',
  REPLACED = 'REPLACED',
  REORGED = 'REORGED'
}
