export interface DataMapRow {
  route: string;
  actor: string;
  component: string;
  fieldGroup: string;
  demoValue: string;
  currentSource: 'FE_STATIC' | 'FE_LOCAL_STATE' | 'BE_DYNAMIC' | 'WALLET_PUBLIC_READ' | 'CHAIN_VIA_BE' | string;
  targetSource: 'FE_STATIC' | 'FE_LOCAL_STATE' | 'BE_DYNAMIC' | 'WALLET_PUBLIC_READ' | 'CHAIN_VIA_BE' | string;
  inputId: string;
  outputId: string;
  viewers: string;
  modifiers: string;
  fetchTrigger: string;
  errorStates: string;
  clientState: string;
  cacheStrategy: string;
  decisionNeeded: string;
}

export const DATA_MAP_ROWS: DataMapRow[] = [
  {
    route: '/ (Home)',
    actor: 'Guest / All',
    component: 'HomePageView / Hero',
    fieldGroup: 'Tiêu đề, slogan, 2 nút CTA',
    demoValue: '"Hiểu nơi đến. Vững bước đi.", Khám phá điểm đến, Tôi muốn đóng góp',
    currentSource: 'FE_STATIC',
    targetSource: 'FE_STATIC',
    inputId: 'Không',
    outputId: 'Không',
    viewers: 'Công chúng',
    modifiers: 'Admin (CMS)',
    fetchTrigger: 'Khi tải trang / đổi ngôn ngữ',
    errorStates: 'Fallback i18n chữ Việt',
    clientState: 'None',
    cacheStrategy: 'SSG / Prerender',
    decisionNeeded: 'Copywriting đã chuẩn chưa hay cần CMS quản lý',
  },
  {
    route: '/ (Home)',
    actor: 'Guest / All',
    component: 'ContributeDialog',
    fieldGroup: '4 hướng đóng góp: Viết bài, Điểm mới, Thẩm định, Quỹ',
    demoValue: '4 thẻ điều hướng kèm mô tả và link',
    currentSource: 'FE_STATIC',
    targetSource: 'FE_STATIC',
    inputId: 'Không',
    outputId: 'Không',
    viewers: 'Công chúng',
    modifiers: 'Nội bộ FE',
    fetchTrigger: 'Khi mở modal',
    errorStates: 'None',
    clientState: 'Dialog Open state',
    cacheStrategy: 'Client component',
    decisionNeeded: '4 luồng này đã đủ rõ ràng chưa',
  },
  {
    route: '/ (Home)',
    actor: 'Guest / All',
    component: 'HomePageView / Highlights',
    fieldGroup: 'Danh sách điểm đến tiêu biểu',
    demoValue: 'Cát Cò 3, Móng Rồng, Tây Côn Lĩnh',
    currentSource: 'FE_STATIC',
    targetSource: 'BE_DYNAMIC',
    inputId: 'Không',
    outputId: 'Tái dùng placeId',
    viewers: 'Công chúng',
    modifiers: 'Admin / System',
    fetchTrigger: 'Khi render Home',
    errorStates: 'Skeleton cards',
    clientState: 'None',
    cacheStrategy: 'ISR (revalidate 1h)',
    decisionNeeded: 'Tiêu chí chọn điểm nổi bật (tự động hay ghim)',
  },
  {
    route: 'AppShell (All)',
    actor: 'All',
    component: 'AppShell / Nav',
    fieldGroup: 'Header brand, logo, search input, links',
    demoValue: 'Khám phá, Vùng dã ngoại, Minh bạch, Ủng hộ, Tài khoản',
    currentSource: 'FE_STATIC',
    targetSource: 'FE_STATIC',
    inputId: 'Không',
    outputId: 'Không',
    viewers: 'Công chúng',
    modifiers: 'Nội bộ FE',
    fetchTrigger: 'Tải layout',
    errorStates: 'Hiển thị navbar rút gọn',
    clientState: 'Mobile drawer state',
    cacheStrategy: 'Prerender',
    decisionNeeded: 'Cấu trúc menu trên mobile đã gọn chưa',
  },
  {
    route: 'AppShell (All)',
    actor: 'All',
    component: 'AppShell / PersonaSwitcher',
    fieldGroup: 'Chuyển đổi vai trò demo',
    demoValue: 'Guest, Member, Author (Minh), VIP (Lan), Expert (Hoàng), Admin (Linh)',
    currentSource: 'FE_LOCAL_STATE',
    targetSource: 'FE_LOCAL_STATE',
    inputId: 'Không',
    outputId: 'userId',
    viewers: 'Reviewer / Dev',
    modifiers: 'User',
    fetchTrigger: 'Tức thì khi click',
    errorStates: 'Giữ nguyên persona',
    clientState: 'LocalStorage ventlore_persona',
    cacheStrategy: 'Client Only',
    decisionNeeded: 'Chỉ hiển thị ở môi trường Dev / Staging',
  },
  {
    route: 'AppShell (All)',
    actor: 'Member+',
    component: 'AppShell / UserMenu',
    fieldGroup: 'Menu hồ sơ & thông báo',
    demoValue: 'Avatar, Handle, Badge vai trò, Đóng góp của tôi, Thoát',
    currentSource: 'FE_LOCAL_STATE',
    targetSource: 'BE_DYNAMIC',
    inputId: 'userId',
    outputId: 'Tái dùng userId',
    viewers: 'User đăng nhập',
    modifiers: 'User',
    fetchTrigger: 'Khi session thay đổi',
    errorStates: 'Chế độ Guest (Đăng nhập)',
    clientState: 'Cookie session',
    cacheStrategy: 'SSR / Client query',
    decisionNeeded: 'Có cần hiển thị số dư ví ngay trên avatar menu',
  },
  {
    route: '/explore',
    actor: 'All',
    component: 'SearchFilters',
    fieldGroup: 'Bộ lọc vùng, hoạt động, độ khó',
    demoValue: 'Miền núi phía Bắc, Ven biển; Trekking, Kayak',
    currentSource: 'FE_STATIC',
    targetSource: 'BE_DYNAMIC',
    inputId: 'Không',
    outputId: 'Tái dùng regionId',
    viewers: 'Công chúng',
    modifiers: 'Admin',
    fetchTrigger: 'Tải trang Explore',
    errorStates: 'Dropdown mặc định',
    clientState: 'URL SearchParams (?region=...)',
    cacheStrategy: 'Client state + query',
    decisionNeeded: 'Danh mục vùng có cần thêm cấp huyện/xã',
  },
  {
    route: '/explore',
    actor: 'All',
    component: 'PlaceResults',
    fieldGroup: 'Lưới thẻ điểm đến, badges cảnh báo',
    demoValue: 'Ảnh, Tên, Vùng, Số bài, Nhãn an toàn',
    currentSource: 'FE_STATIC',
    targetSource: 'BE_DYNAMIC',
    inputId: 'Search filters',
    outputId: 'Tái dùng placeId',
    viewers: 'Công chúng',
    modifiers: 'System',
    fetchTrigger: 'Khi thay đổi bộ lọc',
    errorStates: '"Không tìm thấy địa điểm phù hợp"',
    clientState: 'URL query',
    cacheStrategy: 'Client cache / SWR',
    decisionNeeded: 'Phân trang bằng Infinite scroll hay Nút bấm',
  },
  {
    route: '/explore',
    actor: 'All',
    component: 'PlaceMap',
    fieldGroup: 'Bản đồ tương tác Leaflet / Pins',
    demoValue: 'Tọa độ GPS, Markers, Popup card',
    currentSource: 'FE_STATIC',
    targetSource: 'BE_DYNAMIC',
    inputId: 'Bounding box',
    outputId: 'Tái dùng placeId',
    viewers: 'Công chúng',
    modifiers: 'System',
    fetchTrigger: 'Khi pan/zoom map',
    errorStates: 'Bản đồ xám, giữ pin cũ',
    clientState: 'Viewport lat/lng',
    cacheStrategy: 'Client Only (no SSR)',
    decisionNeeded: 'Nhà cung cấp bản đồ (OpenStreetMap vs Mapbox)',
  },
  {
    route: '/places/[placeId]',
    actor: 'All',
    component: 'PlaceSummary',
    fieldGroup: 'Tên điểm, cảnh báo, tọa độ, mô tả',
    demoValue: 'Vịnh Cát Cò 3, Cảnh báo dòng chảy xiết ngầm',
    currentSource: 'FE_STATIC',
    targetSource: 'BE_DYNAMIC',
    inputId: 'placeId',
    outputId: 'Tái dùng placeId',
    viewers: 'Công chúng',
    modifiers: 'Chuyên gia / Admin',
    fetchTrigger: 'Khi vào trang điểm',
    errorStates: '404 Place Not Found',
    clientState: 'None',
    cacheStrategy: 'SSG + ISR',
    decisionNeeded: 'Cảnh báo khẩn cấp có cần nút chia sẻ nhanh',
  },
  {
    route: '/posts/[postId]',
    actor: 'All',
    component: 'PostReader',
    fieldGroup: 'Bài viết, tác giả, ngày quan sát',
    demoValue: 'Tiêu đề, Tác giả Minh, Ngày 15/06/2026, Nội dung MD',
    currentSource: 'FE_STATIC',
    targetSource: 'BE_DYNAMIC',
    inputId: 'postId, revisionId',
    outputId: 'Tái dùng postId, revisionId',
    viewers: 'Công chúng',
    modifiers: 'Tác giả gốc',
    fetchTrigger: 'Khi vào xem bài',
    errorStates: 'Lỗi tải bài, nội dung ẩn',
    clientState: 'Active revision query',
    cacheStrategy: 'SSG + ISR',
    decisionNeeded: 'VIP content làm mờ (blur) hay cắt ngắn',
  },
  {
    route: '/posts/[postId]',
    actor: 'All',
    component: 'VerificationPanel',
    fieldGroup: 'Huy hiệu kiểm định, phạm vi, hạn dùng',
    demoValue: 'VERIFIED, 15/06/2026 - 15/06/2027, Phạm vi an toàn',
    currentSource: 'FE_STATIC',
    targetSource: 'BE_DYNAMIC',
    inputId: 'revisionId',
    outputId: 'Tái dùng decisionId',
    viewers: 'Công chúng',
    modifiers: 'Ban điều hành',
    fetchTrigger: 'Cùng với post',
    errorStates: 'UNVERIFIED (Chưa kiểm định)',
    clientState: 'None',
    cacheStrategy: 'Prerender',
    decisionNeeded: 'Thể hiện trạng thái EXPIRED (Hết hạn) thế nào',
  },
  {
    route: '/posts/[postId]',
    actor: 'All',
    component: 'PostReader / TipCTA',
    fieldGroup: 'Nút "Tip tác giả", tỷ lệ 80/20',
    demoValue: 'Nút Tip Author, mở PaymentModal POST_TIP',
    currentSource: 'FE_STATIC',
    targetSource: 'BE_DYNAMIC + CHAIN_VIA_BE',
    inputId: 'postId, revisionId',
    outputId: 'routeId',
    viewers: 'Công chúng',
    modifiers: 'Tác giả (consent)',
    fetchTrigger: 'Khi render bài',
    errorStates: 'Nút mờ + Lý do chặn',
    clientState: 'Modal trigger',
    cacheStrategy: 'Client component',
    decisionNeeded: 'Có cho phép tip bằng ETH hay chỉ USDC',
  },
  {
    route: '/posts/[postId]',
    actor: 'All',
    component: 'ReportDialog',
    fieldGroup: 'Form báo cáo thông tin sai lệch',
    demoValue: 'Nhận định claim, lý do báo sai, link dẫn chứng',
    currentSource: 'FE_LOCAL_STATE',
    targetSource: 'BE_DYNAMIC',
    inputId: 'postId, claimId',
    outputId: 'Sinh reportId (UUIDv7)',
    viewers: 'Thành viên',
    modifiers: 'Thành viên báo',
    fetchTrigger: 'Khi bấm Báo sai',
    errorStates: 'Khóa nút khi đang gửi',
    clientState: 'Form state',
    cacheStrategy: 'Client Modal',
    decisionNeeded: 'Người dùng ẩn danh có được gửi report không',
  },
  {
    route: 'PaymentModal',
    actor: 'All',
    component: 'PaymentModal',
    fieldGroup: 'Khung thanh toán chung (3 modes)',
    demoValue: 'PROJECT, POST_TIP, MEMBERSHIP; Lưới mạng Arbitrum',
    currentSource: 'FE_LOCAL_STATE',
    targetSource: 'WALLET_PUBLIC_READ + BE_DYNAMIC',
    inputId: 'Mode, targetId',
    outputId: 'Sinh paymentId / donationId',
    viewers: 'Người thanh toán',
    modifiers: 'Người thanh toán',
    fetchTrigger: 'Khi bấm nút mở modal',
    errorStates: 'Sai mạng, thiếu gas, thiếu token',
    clientState: 'Context state',
    cacheStrategy: 'Client Modal',
    decisionNeeded: 'Cho phép nhập số tiền USD tự do hay theo preset',
  },
  {
    route: 'PaymentModal',
    actor: 'All',
    component: 'PaymentModal / WalletConnect',
    fieldGroup: 'Trạng thái ví Web3',
    demoValue: '0x71C...3aF8, Arbitrum One, Số dư 120 USDC',
    currentSource: 'WALLET_PUBLIC_READ',
    targetSource: 'WALLET_PUBLIC_READ',
    inputId: 'Provider',
    outputId: 'Không',
    viewers: 'Người thanh toán',
    modifiers: 'User (đổi ví)',
    fetchTrigger: 'Khi kết nối ví',
    errorStates: '"Chưa kết nối ví", "Sai mạng"',
    clientState: 'Injected provider',
    cacheStrategy: 'Client Only',
    decisionNeeded: 'Wallet kit ưu tiên (RainbowKit vs AppKit)',
  },
  {
    route: '/vip',
    actor: 'All',
    component: 'VipPage / PricingCard',
    fieldGroup: 'Giá gói, kỳ hạn, danh sách đặc quyền',
    demoValue: '15 USD / 12 tháng lịch UTC; Mở khóa báo cáo sâu',
    currentSource: 'FE_STATIC',
    targetSource: 'BE_DYNAMIC (Plan config)',
    inputId: 'planCode',
    outputId: 'Không',
    viewers: 'Công chúng',
    modifiers: 'Admin cấu hình',
    fetchTrigger: 'Tải trang VIP',
    errorStates: 'Giá mặc định $15',
    clientState: 'None',
    cacheStrategy: 'SSG / ISR',
    decisionNeeded: 'Có áp dụng chính sách giảm giá theo vùng không',
  },
  {
    route: '/vip',
    actor: 'Member+',
    component: 'VipPage / SubCTA',
    fieldGroup: 'Nút Đăng ký / Gia hạn gói VIP',
    demoValue: 'Mở PaymentModal MEMBERSHIP ($15)',
    currentSource: 'FE_LOCAL_STATE',
    targetSource: 'BE_DYNAMIC',
    inputId: 'userId, planCode',
    outputId: 'Sinh paymentId',
    viewers: 'Hội viên',
    modifiers: 'Hội viên',
    fetchTrigger: 'Khi bấm mua/gia hạn',
    errorStates: 'Đăng nhập trước',
    clientState: 'Modal state',
    cacheStrategy: 'Client component',
    decisionNeeded: 'Gia hạn trước hạn có cộng dồn thời gian không',
  },
  {
    route: '/contribute',
    actor: 'Member+',
    component: 'ContributeView / Tab1',
    fieldGroup: 'Form viết bài cho điểm có sẵn',
    demoValue: 'Chọn Place, Tiêu đề, Loại bài, Markdown, Claims',
    currentSource: 'FE_LOCAL_STATE',
    targetSource: 'BE_DYNAMIC',
    inputId: 'placeId',
    outputId: 'Sinh postId + revisionId',
    viewers: 'Tác giả',
    modifiers: 'Tác giả',
    fetchTrigger: 'Tải danh sách places',
    errorStates: 'Lỗi 409 xung đột phiên bản',
    clientState: 'LocalStorage draft',
    cacheStrategy: 'Client form',
    decisionNeeded: 'Cho phép lưu nháp trên server (BE Draft) không',
  },
  {
    route: '/contribute',
    actor: 'Member+',
    component: 'ContributeView / Tab2',
    fieldGroup: 'Form đề xuất điểm mới',
    demoValue: 'Tên điểm, Vùng, Tọa độ GPS, Cảnh báo, Bài khám phá',
    currentSource: 'FE_LOCAL_STATE',
    targetSource: 'BE_DYNAMIC',
    inputId: 'regionId',
    outputId: 'Sinh placeId + postId + revisionId',
    viewers: 'Tác giả',
    modifiers: 'Tác giả',
    fetchTrigger: 'Tức thì khi nhập',
    errorStates: 'Trùng lặp tiềm năng',
    clientState: 'LocalStorage draft',
    cacheStrategy: 'Client form',
    decisionNeeded: 'Ngưỡng khoảng cách GPS cảnh báo trùng (mét)',
  },
  {
    route: '/contribute',
    actor: 'Member+',
    component: 'ContributeView / Duplicate',
    fieldGroup: 'Hộp cảnh báo điểm trùng lặp',
    demoValue: '"Phát hiện điểm tương tự: Vịnh Cát Cò 3 (85%)"',
    currentSource: 'FE_LOCAL_STATE',
    targetSource: 'BE_DYNAMIC',
    inputId: 'Tên điểm gõ vào',
    outputId: 'Tái dùng placeId trùng',
    viewers: 'Tác giả',
    modifiers: 'System',
    fetchTrigger: 'Khi người dùng gõ tên',
    errorStates: 'None',
    clientState: 'Inline warning',
    cacheStrategy: 'Client check',
    decisionNeeded: 'Cho phép bỏ qua cảnh báo để tạo điểm mới',
  },
  {
    route: '/account',
    actor: 'Member+',
    component: 'AccountView / Profile',
    fieldGroup: 'Hồ sơ cá nhân & UUIDv7',
    demoValue: 'Tên, Handle, userId, Vai trò hệ thống',
    currentSource: 'FE_LOCAL_STATE',
    targetSource: 'BE_DYNAMIC',
    inputId: 'userId',
    outputId: 'Tái dùng userId',
    viewers: 'User sở hữu',
    modifiers: 'User',
    fetchTrigger: 'Tải trang cá nhân',
    errorStates: 'Chưa đăng nhập -> redirect',
    clientState: 'Cookie session',
    cacheStrategy: 'SSR / Client query',
    decisionNeeded: 'Trường thông tin nào công khai ra ngoài',
  },
  {
    route: '/account',
    actor: 'Member+',
    component: 'AccountView / Wallet',
    fieldGroup: 'Khung liên kết ví Web3',
    demoValue: '0x71C...3aF8, Arbitrum Sepolia, Đã xác minh',
    currentSource: 'WALLET_PUBLIC_READ',
    targetSource: 'BE_DYNAMIC + WALLET_PUBLIC_READ',
    inputId: 'userId',
    outputId: 'Sinh walletBindingId',
    viewers: 'User sở hữu',
    modifiers: 'User',
    fetchTrigger: 'Tải trang cá nhân',
    errorStates: '"Chưa liên kết ví Web3"',
    clientState: 'None',
    cacheStrategy: 'Client query',
    decisionNeeded: 'Yêu cầu ký thông điệp SIWE khi liên kết ví',
  },
  {
    route: '/account',
    actor: 'Member+',
    component: 'AccountView / MyContribs',
    fieldGroup: 'Danh sách bài & điểm đã nộp',
    demoValue: 'Mã PST, Trạng thái (UNVERIFIED, REVIEW_ONLY)',
    currentSource: 'FE_LOCAL_STATE',
    targetSource: 'BE_DYNAMIC',
    inputId: 'userId',
    outputId: 'Tái dùng postId',
    viewers: 'User sở hữu',
    modifiers: 'Tác giả',
    fetchTrigger: 'Tải tab đóng góp',
    errorStates: '"Chưa có bài đóng góp nào"',
    clientState: 'Query tab',
    cacheStrategy: 'Client query',
    decisionNeeded: 'Có cho phép xóa bài đã gửi không (Invariant cấm)',
  },
  {
    route: '/account',
    actor: 'Member+',
    component: 'AccountView / NewRevision',
    fieldGroup: 'Drawer nộp bản sửa đổi',
    demoValue: 'Tiêu đề mới, Ghi chú sửa đổi theo yêu cầu',
    currentSource: 'FE_LOCAL_STATE',
    targetSource: 'BE_DYNAMIC',
    inputId: 'postId, parent revisionId',
    outputId: 'Sinh revisionId mới (v+1)',
    viewers: 'Tác giả',
    modifiers: 'Tác giả',
    fetchTrigger: 'Khi bấm nộp sửa đổi',
    errorStates: 'Lỗi lưu bản ghi',
    clientState: 'Drawer form',
    cacheStrategy: 'Client modal',
    decisionNeeded: 'Có cho phép sửa tiêu đề bài viết gốc không',
  },
  {
    route: '/account',
    actor: 'Member+',
    component: 'AccountView / VIPTab',
    fieldGroup: 'Tình trạng gói VIP & Nút gia hạn',
    demoValue: 'ACTIVE, Còn 280 ngày, Hạn 15/06/2027',
    currentSource: 'FE_LOCAL_STATE',
    targetSource: 'BE_DYNAMIC',
    inputId: 'userId',
    outputId: 'Tái dùng membershipId',
    viewers: 'User sở hữu',
    modifiers: 'User',
    fetchTrigger: 'Tải tab VIP',
    errorStates: 'Hết hạn (EXPIRED)',
    clientState: 'Query tab',
    cacheStrategy: 'Client query',
    decisionNeeded: 'Thông báo nhắc gia hạn trước bao nhiêu ngày',
  },
  {
    route: '/account',
    actor: 'Member+',
    component: 'AccountView / Benefits',
    fieldGroup: 'Bốn khối quyền lợi sau duyệt',
    demoValue: '1. Nhãn web; 2. SBT; 3. NFT; 4. Tip Route 80/20',
    currentSource: 'FE_LOCAL_STATE',
    targetSource: 'CHAIN_VIA_BE + BE_DYNAMIC',
    inputId: 'userId',
    outputId: 'Tái dùng credentialId / collectibleId',
    viewers: 'Tác giả',
    modifiers: 'Tác giả',
    fetchTrigger: 'Tải tab quyền lợi',
    errorStates: 'Chưa đủ điều kiện (Not Eligible)',
    clientState: 'Query tab',
    cacheStrategy: 'Client query',
    decisionNeeded: 'Claim SBT/NFT có yêu cầu người dùng trả gas không',
  },
  {
    route: '/expert',
    actor: 'Expert',
    component: 'ExpertWorkspaceView / Tasks',
    fieldGroup: 'Bảng việc thực địa (5 trạng thái)',
    demoValue: 'Offered, In Progress, Submitted, Accepted Work',
    currentSource: 'FE_LOCAL_STATE',
    targetSource: 'BE_DYNAMIC',
    inputId: 'expertUserId',
    outputId: 'Tái dùng taskId',
    viewers: 'Chuyên gia',
    modifiers: 'Chuyên gia',
    fetchTrigger: 'Tải trang Expert',
    errorStates: '"Không có nhiệm vụ nào"',
    clientState: 'Subfilter state',
    cacheStrategy: 'Client query',
    decisionNeeded: 'Hạn chót từ chối nhận việc (bao nhiêu giờ)',
  },
  {
    route: '/expert',
    actor: 'Expert',
    component: 'ExpertWorkspaceView / Evidence',
    fieldGroup: 'Modal nộp bằng chứng & đánh giá claims',
    demoValue: 'Khảo sát từng claim (Đúng/Sai), Kết luận, Ảnh URL',
    currentSource: 'FE_LOCAL_STATE',
    targetSource: 'BE_DYNAMIC',
    inputId: 'taskId',
    outputId: 'Sinh submissionId',
    viewers: 'Chuyên gia',
    modifiers: 'Chuyên gia',
    fetchTrigger: 'Khi bấm nộp báo cáo',
    errorStates: 'Khóa nút khi gửi',
    clientState: 'Form modal',
    cacheStrategy: 'Client modal',
    decisionNeeded: 'Định dạng tệp ảnh đối chứng (JPEG/GPX tracklog)',
  },
  {
    route: '/expert',
    actor: 'Expert',
    component: 'ExpertWorkspaceView / Payables',
    fieldGroup: 'Bảng công phải nhận',
    demoValue: 'Mã công nợ, Thù lao (50 USDC), OPEN, PAID',
    currentSource: 'FE_LOCAL_STATE',
    targetSource: 'CHAIN_VIA_BE + BE_DYNAMIC',
    inputId: 'expertUserId',
    outputId: 'Sinh payableId',
    viewers: 'Chuyên gia',
    modifiers: 'Ban điều hành',
    fetchTrigger: 'Tải tab payables',
    errorStates: '"Chưa có công nợ nào"',
    clientState: 'Tab state',
    cacheStrategy: 'Client query',
    decisionNeeded: 'Cơ chế chi trả thù lao (Batch payout hay từng task)',
  },
  {
    route: '/admin',
    actor: 'Admin',
    component: 'AdminWorkspaceView / Intake',
    fieldGroup: 'Tiếp nhận hồ sơ & khiếu nại',
    demoValue: 'Danh sách candidate places, bài viết mới, báo sai',
    currentSource: 'FE_LOCAL_STATE',
    targetSource: 'BE_DYNAMIC',
    inputId: 'Không',
    outputId: 'Tái dùng intakeId',
    viewers: 'Ban điều hành',
    modifiers: 'Ban điều hành',
    fetchTrigger: 'Tải trang Admin',
    errorStates: 'Hàng đợi trống',
    clientState: 'Tab state',
    cacheStrategy: 'Client query',
    decisionNeeded: 'Quy trình tự động phân luồng theo vùng địa lý',
  },
  {
    route: '/admin',
    actor: 'Admin',
    component: 'AdminWorkspaceView / Compare',
    fieldGroup: 'Popup đối chiếu điểm trùng',
    demoValue: 'So sánh Tên, Vùng, Tọa độ giữa bài nộp và hệ thống',
    currentSource: 'FE_LOCAL_STATE',
    targetSource: 'BE_DYNAMIC',
    inputId: 'intakeId, placeId',
    outputId: 'Không',
    viewers: 'Ban điều hành',
    modifiers: 'Ban điều hành',
    fetchTrigger: 'Khi bấm So sánh',
    errorStates: 'Không có điểm trùng',
    clientState: 'Modal state',
    cacheStrategy: 'Client modal',
    decisionNeeded: 'Quyền gộp điểm thuộc Admin hay Chuyên gia',
  },
  {
    route: '/admin',
    actor: 'Admin',
    component: 'AdminWorkspaceView / Assign',
    fieldGroup: 'Modal giao việc cho chuyên gia',
    demoValue: 'Chọn Chuyên gia Hoàng, Hạn 7 ngày, Thù lao 50 USDC',
    currentSource: 'FE_LOCAL_STATE',
    targetSource: 'BE_DYNAMIC',
    inputId: 'caseId',
    outputId: 'Sinh taskId',
    viewers: 'Ban điều hành',
    modifiers: 'Ban điều hành',
    fetchTrigger: 'Khi bấm Giao việc',
    errorStates: 'Không có chuyên gia rảnh',
    clientState: 'Form modal',
    cacheStrategy: 'Client modal',
    decisionNeeded: 'Ngân sách trích thù lao lấy từ Quỹ nào',
  },
  {
    route: '/admin',
    actor: 'Admin',
    component: 'AdminWorkspaceView / WorkAccept',
    fieldGroup: 'Nghiệm thu chất lượng công việc (QĐ 1)',
    demoValue: 'ACCEPTED_WORK hoặc REJECTED_WORK kèm lý do',
    currentSource: 'FE_LOCAL_STATE',
    targetSource: 'BE_DYNAMIC',
    inputId: 'taskId',
    outputId: 'Sinh payableId (nếu ACCEPTED)',
    viewers: 'Ban điều hành',
    modifiers: 'Ban điều hành',
    fetchTrigger: 'Khi xem submission',
    errorStates: 'Ghi nhận thất bại',
    clientState: 'Modal state',
    cacheStrategy: 'Client modal',
    decisionNeeded: 'Bất biến: Công đạt độc lập với kết luận bài',
  },
  {
    route: '/admin',
    actor: 'Admin',
    component: 'AdminWorkspaceView / ContentDecide',
    fieldGroup: 'Quyết định nội dung bài viết (QĐ 2)',
    demoValue: 'APPROVED, REJECTED, CHANGES_REQUESTED',
    currentSource: 'FE_LOCAL_STATE',
    targetSource: 'BE_DYNAMIC',
    inputId: 'caseId',
    outputId: 'Sinh decisionId',
    viewers: 'Ban điều hành',
    modifiers: 'Ban điều hành',
    fetchTrigger: 'Sau khi chuyên gia nộp',
    errorStates: 'Ghi nhận quyết định',
    clientState: 'Modal state',
    cacheStrategy: 'Client modal',
    decisionNeeded: 'Bác bài có cho phép tác giả nộp lại revision mới',
  },
  {
    route: '/admin',
    actor: 'Admin',
    component: 'AdminWorkspaceView / Hold',
    fieldGroup: 'Bật / Tắt App Hold khẩn cấp',
    demoValue: 'Khóa luồng tip và gắn cờ cảnh báo trên UI',
    currentSource: 'FE_LOCAL_STATE',
    targetSource: 'BE_DYNAMIC + CHAIN_VIA_BE',
    inputId: 'revisionId',
    outputId: 'Cập nhật cờ hold',
    viewers: 'Ban điều hành',
    modifiers: 'Ban điều hành',
    fetchTrigger: 'Khi bấm nút Hold',
    errorStates: 'Thất bại kết nối',
    clientState: 'Switch state',
    cacheStrategy: 'Client action',
    decisionNeeded: 'Thời gian tối đa giữ trạng thái App Hold',
  },
  {
    route: '/transparency',
    actor: 'All',
    component: 'PublicLedger',
    fieldGroup: 'Sổ cái công khai số dư quỹ & nguồn thu',
    demoValue: '45.200 USDC, 3.4 ETH; Quỹ dự án, Phí hội viên',
    currentSource: 'FE_STATIC',
    targetSource: 'CHAIN_VIA_BE + BE_DYNAMIC',
    inputId: 'Không',
    outputId: 'Không',
    viewers: 'Công chúng',
    modifiers: 'System',
    fetchTrigger: 'Tải trang Minh bạch',
    errorStates: 'Bảng rỗng',
    clientState: 'Year selector',
    cacheStrategy: 'SSG + ISR (1h)',
    decisionNeeded: 'Tần suất worker đồng bộ số dư onchain',
  },
  {
    route: '/transparency',
    actor: 'All',
    component: 'PublicLedger / Stream',
    fieldGroup: 'Nhật ký giao dịch mô phỏng live',
    demoValue: 'Danh sách đơn thanh toán: POST_TIP, DONATION, VIP',
    currentSource: 'FE_LOCAL_STATE',
    targetSource: 'CHAIN_VIA_BE + BE_DYNAMIC',
    inputId: 'Không',
    outputId: 'Tái dùng paymentId',
    viewers: 'Công chúng',
    modifiers: 'System',
    fetchTrigger: 'Polling 3s một lần',
    errorStates: '"Chưa có giao dịch nào"',
    clientState: 'Polling state',
    cacheStrategy: 'Client live query',
    decisionNeeded: 'Giới hạn số dòng hiển thị công khai (20 hay 50)',
  },
  {
    route: 'Floating',
    actor: 'Reviewer',
    component: 'ReviewToolbar',
    fieldGroup: 'Khung điều khiển nghiệm thu 14 kịch bản',
    demoValue: '14 kịch bản, Nút chuyển persona, Lối tắt nhanh',
    currentSource: 'FE_LOCAL_STATE',
    targetSource: 'FE_LOCAL_STATE',
    inputId: 'Không',
    outputId: 'Không',
    viewers: 'Bin / QA Reviewer',
    modifiers: 'Reviewer',
    fetchTrigger: 'Tải mọi trang',
    errorStates: 'Thu gọn thành icon pill',
    clientState: 'Widget Open state',
    cacheStrategy: 'Client Only',
    decisionNeeded: 'Tắt hoàn toàn khi đóng gói bản Production',
  },
];

export const KEY_DECISIONS = [
  {
    number: 1,
    title: 'Lưu trữ bản nháp (Draft persistence)',
    description: 'Hiện tại nháp bài viết và địa điểm mới lưu tại localStorage của trình duyệt người dùng. Sau này có cần hỗ trợ đồng bộ nháp lên máy chủ (BE Draft) khi tác giả đổi máy tính hoặc điện thoại không?',
    recommendation: 'Đề xuất hỗ trợ LocalStorage trước trong MVP; lưu BE draft ở phiên bản tiếp theo khi người dùng bấm Lưu nháp có chủ đích.',
  },
  {
    number: 2,
    title: 'Quyền truy cập nội dung VIP (VIP Content Access)',
    description: 'Mức độ hiển thị nội dung VIP đối với Guest và Member thường: Làm mờ các đoạn văn cảnh báo chuyên sâu (blur) hay chỉ hiển thị tóm tắt và ẩn hoàn toàn phần nhận định chi tiết?',
    recommendation: 'Đề xuất làm mờ kèm nút Mở khóa VIP để tăng tỷ lệ chuyển đổi hội viên và kích thích tò mò.',
  },
  {
    number: 3,
    title: 'Cảnh báo điểm trùng lặp (Duplicate Place Threshold)',
    description: 'Ngưỡng khoảng cách GPS (ví dụ 100m hay 500m) và độ tương đồng tên gọi: Khi phát hiện khả năng trùng lặp, người dùng có quyền tự quyết định tiếp tục tạo mới hay bắt buộc chuyển qua Admin duyệt?',
    recommendation: 'Cảnh báo màu cam và gợi ý chuyển sang viết bài cho điểm có sẵn, nhưng cho phép tiếp tục nếu người dùng xác nhận đây là điểm riêng biệt.',
  },
  {
    number: 4,
    title: 'Chi trả thù lao Chuyên gia (Expert Payables Release)',
    description: 'Việc giải ngân từ Quỹ dự án cho các chuyên gia có công nợ OPEN sẽ thực hiện tự động qua Smart Contract định kỳ hàng tuần, hay Admin ký duyệt chi thủ công từng khoản?',
    recommendation: 'Admin ký lệnh duyệt chi theo đợt (Batch Payout) để tối ưu chi phí gas trên mạng Arbitrum.',
  },
  {
    number: 5,
    title: 'Tiền tệ Tip & Quyên góp (Tip & Donation Currencies)',
    description: 'Ventlore hỗ trợ thanh toán tip và quyên góp bằng token ERC-20 (USDC) trên Arbitrum. Có cần mở rộng thêm native token (ETH) hay giải pháp thanh toán thẻ nội địa qua cổng trung gian không?',
    recommendation: 'Khởi đầu với USDC trên Arbitrum One vì giá trị ổn định 1:1 USD, phí gas siêu rẻ (< 0.05 USD).',
  },
];

export const RAW_FE_DATA_MAP_MD = `# Ventlore · FE Data Map (Bản Đồ Quyết Định Dữ Liệu Tĩnh / Động)

Tài liệu này xác lập chi tiết từng component và nhóm trường dữ liệu trên toàn bộ giao diện Front-End Ventlore. Đây là cơ sở cốt lõi để Đội ngũ Kỹ thuật đối chiếu và phát triển Backend (BE), Database, Indexer và Smart Contract sau khi Chủ dự án (Bin) nghiệm thu giao diện.

---

## 1. Phân loại Nguồn Đích (Target Data Sources)

- \`FE_STATIC\`: Dữ liệu tĩnh, bản dịch i18n, copywriting, brand assets, constants cục bộ.
- \`FE_LOCAL_STATE\`: Trạng thái tương tác tạm thời của người dùng trên trình duyệt (URL query, form input nháp, tab đang chọn, filter, trạng thái mở modal).
- \`BE_DYNAMIC\`: Dữ liệu nghiệp vụ động lưu tại cơ sở dữ liệu PostgreSQL và trả về qua REST API (\`/api/v1\`).
- \`WALLET_PUBLIC_READ\`: Dữ liệu công khai đọc trực tiếp từ Web3 Provider / RPC (Địa chỉ ví đang kết nối, Chain ID, số dư token ERC-20/ETH, allowance).
- \`CHAIN_VIA_BE\`: Dữ liệu onchain (Smart Contract events, Splitter receipt, SBT/NFT mint transaction) đã được Indexer/Worker quét, giải mã và trả về qua API tổng hợp có thẩm quyền.

---

## 2. Bảng Ma Trận Dữ Liệu Chi Tiết (16 Cột Chuẩn Hóa)

| Page/route | Actor | Component | Field/data group | Giá trị demo | Nguồn đang dùng | Nguồn đích đề xuất | ID đầu vào | ID tạo/sử dụng lại | Ai xem | Ai sửa | Khi nào tải/làm mới | Trạng thái lỗi/rỗng/chờ | Client state/persist | Gợi ý cache/render | Quyết định cần Bin chốt |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| \`/\` (Home) | Guest / All | \`HomePageView\` / Hero | Tiêu đề, slogan, 2 nút CTA | "Hiểu nơi đến. Vững bước đi.", Khám phá điểm đến, Tôi muốn đóng góp | \`FE_STATIC\` | \`FE_STATIC\` | Không | Không | Công chúng | Admin (CMS) | Khi tải trang / đổi ngôn ngữ | Fallback i18n chữ Việt | None | SSG / Prerender | Copywriting đã chuẩn chưa hay cần CMS quản lý |
| \`/\` (Home) | Guest / All | \`ContributeDialog\` | 4 hướng đóng góp: Viết bài, Điểm mới, Thẩm định, Quỹ | 4 thẻ điều hướng kèm mô tả và link | \`FE_STATIC\` | \`FE_STATIC\` | Không | Không | Công chúng | Nội bộ FE | Khi mở modal | None | Dialog Open state | Client component | 4 luồng này đã đủ rõ ràng chưa |
| \`/\` (Home) | Guest / All | \`HomePageView\` / Highlights | Danh sách điểm đến tiêu biểu | Cát Cò 3, Móng Rồng, Tây Côn Lĩnh | \`api-client\` mock | \`BE_DYNAMIC\` | Không | Tái dùng \`placeId\` | Công chúng | Admin / System | Khi render Home | Skeleton cards | None | ISR (revalidate 1h) | Tiêu chí chọn điểm nổi bật (tự động hay ghim) |
| \`AppShell\` (All) | All | \`AppShell\` / Nav | Header brand, logo, search input, links | Khám phá, Vùng dã ngoại, Minh bạch, Ủng hộ, Tài khoản | \`FE_STATIC\` | \`FE_STATIC\` | Không | Không | Công chúng | Nội bộ FE | Tải layout | Hiển thị navbar rút gọn | Mobile drawer state | Prerender | Cấu trúc menu trên mobile đã gọn chưa |
| \`AppShell\` (All) | All | \`AppShell\` / PersonaSwitcher | Chuyển đổi vai trò demo | Guest, Member, Author (Minh), VIP (Lan), Expert (Hoàng), Admin (Linh) | \`api-client\` mock | \`FE_LOCAL_STATE\` | Không | \`userId\` | Reviewer / Dev | User | Tức thì khi click | Giữ nguyên persona | LocalStorage \`ventlore_persona\` | Client Only | Chỉ hiển thị ở môi trường Dev / Staging |
| \`AppShell\` (All) | Member+ | \`AppShell\` / UserMenu | Menu hồ sơ & thông báo | Avatar, Handle, Badge vai trò, Đóng góp của tôi, Thoát | SessionContext | \`BE_DYNAMIC\` | \`userId\` | Tái dùng \`userId\` | User đăng nhập | User | Khi session thay đổi | Chế độ Guest (Đăng nhập) | Cookie session | SSR / Client query | Có cần hiển thị số dư ví ngay trên avatar menu |
| \`/explore\` | All | \`SearchFilters\` | Bộ lọc vùng, hoạt động, độ khó | Miền núi phía Bắc, Ven biển; Trekking, Kayak | \`FE_STATIC\` | \`BE_DYNAMIC\` (Regions) | Không | Tái dùng \`regionId\` | Công chúng | Admin | Tải trang Explore | Dropdown mặc định | URL SearchParams (\`?region=...\`) | Client state + query | Danh mục vùng có cần thêm cấp huyện/xã |
| \`/explore\` | All | \`PlaceResults\` | Lưới thẻ điểm đến, badges cảnh báo | Ảnh, Tên, Vùng, Số bài, Nhãn an toàn | \`api-client\` mock | \`BE_DYNAMIC\` | Search filters | Tái dùng \`placeId\` | Công chúng | System | Khi thay đổi bộ lọc | "Không tìm thấy địa điểm phù hợp" | URL query | Client cache / SWR | Phân trang bằng Infinite scroll hay Nút bấm |
| \`/explore\` | All | \`PlaceMap\` | Bản đồ tương tác Leaflet / Pins | Tọa độ GPS, Markers, Popup card | \`api-client\` mock | \`BE_DYNAMIC\` | Bounding box | Tái dùng \`placeId\` | Công chúng | System | Khi pan/zoom map | Bản đồ xám, giữ pin cũ | Viewport lat/lng | Client Only (no SSR) | Nhà cung cấp bản đồ (OpenStreetMap vs Mapbox) |
| \`/places/[placeId]\` | All | \`PlaceSummary\` | Tên điểm, cảnh báo, tọa độ, mô tả | Vịnh Cát Cò 3, Cảnh báo dòng chảy xiết ngầm | \`api-client\` mock | \`BE_DYNAMIC\` | \`placeId\` | Tái dùng \`placeId\` | Công chúng | Chuyên gia / Admin | Khi vào trang điểm | 404 Place Not Found | None | SSG + ISR | Cảnh báo khẩn cấp có cần nút chia sẻ nhanh |
| \`/posts/[postId]\` | All | \`PostReader\` | Bài viết, tác giả, ngày quan sát | Tiêu đề, Tác giả Minh, Ngày 15/06/2026, Nội dung MD | \`api-client\` mock | \`BE_DYNAMIC\` | \`postId\`, \`revisionId\` | Tái dùng \`postId\`, \`revisionId\` | Công chúng | Tác giả gốc | Khi vào xem bài | Lỗi tải bài, nội dung ẩn | Active revision query | SSG + ISR | VIP content làm mờ (blur) hay cắt ngắn |
| \`/posts/[postId]\` | All | \`VerificationPanel\` | Huy hiệu kiểm định, phạm vi, hạn dùng | VERIFIED, 15/06/2026 - 15/06/2027, Phạm vi an toàn | \`api-client\` mock | \`BE_DYNAMIC\` | \`revisionId\` | Tái dùng \`decisionId\` | Công chúng | Ban điều hành | Cùng với post | UNVERIFIED (Chưa kiểm định) | None | Prerender | Thể hiện trạng thái EXPIRED (Hết hạn) thế nào |
| \`/posts/[postId]\` | All | \`PostReader\` / TipCTA | Nút "Tip tác giả", tỷ lệ 80/20 | Nút Tip Author, mở PaymentModal POST_TIP | \`api-client\` mock | \`BE_DYNAMIC\` + \`CHAIN_VIA_BE\` | \`postId\`, \`revisionId\` | \`routeId\` | Công chúng | Tác giả (consent) | Khi render bài | Nút mờ + Lý do chặn | Modal trigger | Client component | Có cho phép tip bằng ETH hay chỉ USDC |
| \`/posts/[postId]\` | All | \`ReportDialog\` | Form báo cáo thông tin sai lệch | Nhận định claim, lý do báo sai, link dẫn chứng | \`FE_LOCAL_STATE\` | \`BE_DYNAMIC\` | \`postId\`, \`claimId\` | Sinh \`reportId\` (UUIDv7) | Thành viên | Thành viên báo | Khi bấm Báo sai | Khóa nút khi đang gửi | Form state | Client Modal | Người dùng ẩn danh có được gửi report không |
| \`PaymentModal\` | All | \`PaymentModal\` | Khung thanh toán chung (3 modes) | PROJECT, POST_TIP, MEMBERSHIP; Lưới mạng Arbitrum | \`PaymentContext\` | \`WALLET_PUBLIC_READ\` + \`BE_DYNAMIC\` | Mode, targetId | Sinh \`paymentId\` / \`donationId\` | Người thanh toán | Người thanh toán | Khi bấm nút mở modal | Sai mạng, thiếu gas, thiếu token | Context state | Client Modal | Cho phép nhập số tiền USD tự do hay theo preset |
| \`PaymentModal\` | All | \`PaymentModal\` / WalletConnect | Trạng thái ví Web3 | \`0x71C...3aF8\`, Arbitrum One, Số dư 120 USDC | \`WALLET_PUBLIC_READ\` | \`WALLET_PUBLIC_READ\` | Provider | Không | Người thanh toán | User (đổi ví) | Khi kết nối ví | "Chưa kết nối ví", "Sai mạng" | Injected provider | Client Only | Wallet kit ưu tiên (RainbowKit vs AppKit) |
| \`/vip\` | All | \`VipPage\` / PricingCard | Giá gói, kỳ hạn, danh sách đặc quyền | 15 USD / 12 tháng lịch UTC; Mở khóa báo cáo sâu | \`api-client\` mock | \`BE_DYNAMIC\` (Plan config) | \`planCode\` | Không | Công chúng | Admin cấu hình | Tải trang VIP | Giá mặc định $15 | None | SSG / ISR | Có áp dụng chính sách giảm giá theo vùng không |
| \`/vip\` | Member+ | \`VipPage\` / SubCTA | Nút Đăng ký / Gia hạn gói VIP | Mở PaymentModal MEMBERSHIP ($15) | \`PaymentContext\` | \`BE_DYNAMIC\` | \`userId\`, \`planCode\` | Sinh \`paymentId\` | Hội viên | Hội viên | Khi bấm mua/gia hạn | Đăng nhập trước | Modal state | Client component | Gia hạn trước hạn có cộng dồn thời gian không |
| \`/contribute\` | Member+ | \`ContributeView\` / Tab1 | Form viết bài cho điểm có sẵn | Chọn Place, Tiêu đề, Loại bài, Markdown, Claims | \`FE_LOCAL_STATE\` | \`BE_DYNAMIC\` | \`placeId\` | Sinh \`postId\` + \`revisionId\` | Tác giả | Tác giả | Tải danh sách places | Lỗi 409 xung đột phiên bản | LocalStorage draft | Client form | Cho phép lưu nháp trên server (BE Draft) không |
| \`/contribute\` | Member+ | \`ContributeView\` / Tab2 | Form đề xuất điểm mới | Tên điểm, Vùng, Tọa độ GPS, Cảnh báo, Bài khám phá | \`FE_LOCAL_STATE\` | \`BE_DYNAMIC\` | \`regionId\` | Sinh \`placeId\` + \`postId\` + \`revisionId\` | Tác giả | Tác giả | Tức thì khi nhập | Trùng lặp tiềm năng | LocalStorage draft | Client form | Ngưỡng khoảng cách GPS cảnh báo trùng (mét) |
| \`/contribute\` | Member+ | \`ContributeView\` / Duplicate | Hộp cảnh báo điểm trùng lặp | "Phát hiện điểm tương tự: Vịnh Cát Cò 3 (85%)" | \`FE_LOCAL_STATE\` | \`BE_DYNAMIC\` | Tên điểm gõ vào | Tái dùng \`placeId\` trùng | Tác giả | System | Khi người dùng gõ tên | None | Inline warning | Client check | Cho phép bỏ qua cảnh báo để tạo điểm mới |
| \`/account\` | Member+ | \`AccountView\` / Profile | Hồ sơ cá nhân & UUIDv7 | Tên, Handle, userId, Vai trò hệ thống | SessionContext | \`BE_DYNAMIC\` | \`userId\` | Tái dùng \`userId\` | User sở hữu | User | Tải trang cá nhân | Chưa đăng nhập -> redirect | Cookie session | SSR / Client query | Trường thông tin nào công khai ra ngoài |
| \`/account\` | Member+ | \`AccountView\` / Wallet | Khung liên kết ví Web3 | \`0x71C...3aF8\`, Arbitrum Sepolia, Đã xác minh | \`api-client\` mock | \`BE_DYNAMIC\` + \`WALLET_PUBLIC_READ\` | \`userId\` | Sinh \`walletBindingId\` | User sở hữu | User | Tải trang cá nhân | "Chưa liên kết ví Web3" | None | Client query | Yêu cầu ký thông điệp SIWE khi liên kết ví |
| \`/account\` | Member+ | \`AccountView\` / MyContribs | Danh sách bài & điểm đã nộp | Mã PST, Trạng thái (UNVERIFIED, REVIEW_ONLY) | \`api-client\` mock | \`BE_DYNAMIC\` | \`userId\` | Tái dùng \`postId\` | User sở hữu | Tác giả | Tải tab đóng góp | "Chưa có bài đóng góp nào" | Query tab | Client query | Có cho phép xóa bài đã gửi không (Invariant cấm) |
| \`/account\` | Member+ | \`AccountView\` / NewRevision | Drawer nộp bản sửa đổi | Tiêu đề mới, Ghi chú sửa đổi theo yêu cầu | \`FE_LOCAL_STATE\` | \`BE_DYNAMIC\` | \`postId\`, parent \`revisionId\` | Sinh \`revisionId\` mới (v+1) | Tác giả | Tác giả | Khi bấm nộp sửa đổi | Lỗi lưu bản ghi | Drawer form | Client modal | Có cho phép sửa tiêu đề bài viết gốc không |
| \`/account\` | Member+ | \`AccountView\` / VIPTab | Tình trạng gói VIP & Nút gia hạn | ACTIVE, Còn 280 ngày, Hạn 15/06/2027 | \`api-client\` mock | \`BE_DYNAMIC\` | \`userId\` | Tái dùng \`membershipId\` | User sở hữu | User | Tải tab VIP | Hết hạn (EXPIRED) | Query tab | Client query | Thông báo nhắc gia hạn trước bao nhiêu ngày |
| \`/account\` | Member+ | \`AccountView\` / Benefits | Bốn khối quyền lợi sau duyệt | 1. Nhãn web; 2. SBT; 3. NFT; 4. Tip Route 80/20 | \`api-client\` mock | \`CHAIN_VIA_BE\` + \`BE_DYNAMIC\` | \`userId\` | Tái dùng credentialId / collectibleId | Tác giả | Tác giả | Tải tab quyền lợi | Chưa đủ điều kiện (Not Eligible) | Query tab | Client query | Claim SBT/NFT có yêu cầu người dùng trả gas không |
| \`/expert\` | Expert | \`ExpertWorkspaceView\` / Tasks | Bảng việc thực địa (5 trạng thái) | Offered, In Progress, Submitted, Accepted Work | \`api-client\` mock | \`BE_DYNAMIC\` | \`expertUserId\` | Tái dùng \`taskId\` | Chuyên gia | Chuyên gia | Tải trang Expert | "Không có nhiệm vụ nào" | Subfilter state | Client query | Hạn chót từ chối nhận việc (bao nhiêu giờ) |
| \`/expert\` | Expert | \`ExpertWorkspaceView\` / Evidence | Modal nộp bằng chứng & đánh giá claims | Khảo sát từng claim (Đúng/Sai), Kết luận, Ảnh URL | \`FE_LOCAL_STATE\` | \`BE_DYNAMIC\` | \`taskId\` | Sinh \`submissionId\` | Chuyên gia | Chuyên gia | Khi bấm nộp báo cáo | Khóa nút khi gửi | Form modal | Client modal | Định dạng tệp ảnh đối chứng (JPEG/GPX tracklog) |
| \`/expert\` | Expert | \`ExpertWorkspaceView\` / Payables | Bảng công phải nhận | Mã công nợ, Thù lao (50 USDC), OPEN, PAID | \`api-client\` mock | \`CHAIN_VIA_BE\` + \`BE_DYNAMIC\` | \`expertUserId\` | Sinh \`payableId\` | Chuyên gia | Ban điều hành | Tải tab payables | "Chưa có công nợ nào" | Tab state | Client query | Cơ chế chi trả thù lao (Batch payout hay từng task) |
| \`/admin\` | Admin | \`AdminWorkspaceView\` / Intake | Tiếp nhận hồ sơ & khiếu nại | Danh sách candidate places, bài viết mới, báo sai | \`api-client\` mock | \`BE_DYNAMIC\` | Không | Tái dùng intakeId | Ban điều hành | Ban điều hành | Tải trang Admin | Hàng đợi trống | Tab state | Client query | Quy trình tự động phân luồng theo vùng địa lý |
| \`/admin\` | Admin | \`AdminWorkspaceView\` / Compare | Popup đối chiếu điểm trùng | So sánh Tên, Vùng, Tọa độ giữa bài nộp và hệ thống | \`FE_LOCAL_STATE\` | \`BE_DYNAMIC\` | \`intakeId\`, \`placeId\` | Không | Ban điều hành | Ban điều hành | Khi bấm So sánh | Không có điểm trùng | Modal state | Client modal | Quyền gộp điểm thuộc Admin hay Chuyên gia |
| \`/admin\` | Admin | \`AdminWorkspaceView\` / Assign | Modal giao việc cho chuyên gia | Chọn Chuyên gia Hoàng, Hạn 7 ngày, Thù lao 50 USDC | \`FE_LOCAL_STATE\` | \`BE_DYNAMIC\` | \`caseId\` | Sinh \`taskId\` | Ban điều hành | Ban điều hành | Khi bấm Giao việc | Không có chuyên gia rảnh | Form modal | Client modal | Ngân sách trích thù lao lấy từ Quỹ nào |
| \`/admin\` | Admin | \`AdminWorkspaceView\` / WorkAccept | Nghiệm thu chất lượng công việc (QĐ 1) | ACCEPTED_WORK hoặc REJECTED_WORK kèm lý do | \`FE_LOCAL_STATE\` | \`BE_DYNAMIC\` | \`taskId\` | Sinh \`payableId\` (nếu ACCEPTED) | Ban điều hành | Ban điều hành | Khi xem submission | Ghi nhận thất bại | Modal state | Client modal | Bất biến: Công đạt độc lập với kết luận bài |
| \`/admin\` | Admin | \`AdminWorkspaceView\` / ContentDecide | Quyết định nội dung bài viết (QĐ 2) | APPROVED, REJECTED, CHANGES_REQUESTED | \`FE_LOCAL_STATE\` | \`BE_DYNAMIC\` | \`caseId\` | Sinh \`decisionId\` | Ban điều hành | Ban điều hành | Sau khi chuyên gia nộp | Ghi nhận quyết định | Modal state | Client modal | Bác bài có cho phép tác giả nộp lại revision mới |
| \`/admin\` | Admin | \`AdminWorkspaceView\` / Hold | Bật / Tắt App Hold khẩn cấp | Khóa luồng tip và gắn cờ cảnh báo trên UI | \`api-client\` mock | \`BE_DYNAMIC\` + \`CHAIN_VIA_BE\` | \`revisionId\` | Cập nhật cờ hold | Ban điều hành | Ban điều hành | Khi bấm nút Hold | Thất bại kết nối | Switch state | Client action | Thời gian tối đa giữ trạng thái App Hold |
| \`/transparency\` | All | \`PublicLedger\` | Sổ cái công khai số dư quỹ & nguồn thu | 45.200 USDC, 3.4 ETH; Quỹ dự án, Phí hội viên | \`api-client\` mock | \`CHAIN_VIA_BE\` + \`BE_DYNAMIC\` | Không | Không | Công chúng | System | Tải trang Minh bạch | Bảng rỗng | Year selector | SSG + ISR (1h) | Tần suất worker đồng bộ số dư onchain |
| \`/transparency\` | All | \`PublicLedger\` / Stream | Nhật ký giao dịch mô phỏng live | Danh sách đơn thanh toán: POST_TIP, DONATION, VIP | \`api-client\` mock | \`CHAIN_VIA_BE\` + \`BE_DYNAMIC\` | Không | Tái dùng \`paymentId\` | Công chúng | System | Polling 3s một lần | "Chưa có giao dịch nào" | Polling state | Client live query | Giới hạn số dòng hiển thị công khai (20 hay 50) |
| Floating | Reviewer | \`ReviewToolbar\` | Khung điều khiển nghiệm thu 14 kịch bản | 14 kịch bản, Nút chuyển persona, Lối tắt nhanh | \`FE_LOCAL_STATE\` | \`FE_LOCAL_STATE\` | Không | Không | Bin / QA Reviewer | Reviewer | Tải mọi trang | Thu gọn thành icon pill | Widget Open state | Client Only | Tắt hoàn toàn khi đóng gói bản Production |

---

## 3. Danh sách các Quyết định Kỹ thuật Cần Bin Chốt Sau Khi Trải Nghiệm FE

1. **Lưu trữ bản nháp (Draft persistence):** Hiện tại nháp lưu tại \`localStorage\` của trình duyệt. Sau này có cần đồng bộ nháp lên server (\`BE Draft\`) khi người dùng đổi thiết bị không?
2. **Quyền truy cập VIP Content:** Mức độ hiển thị nội dung VIP với Guest/Member thường: Làm mờ đoạn văn (blur) hay chỉ hiển thị tóm tắt và khóa toàn bộ phần nhận định chi tiết?
3. **Cảnh báo điểm trùng lặp:** Ngưỡng khoảng cách GPS và độ tương đồng tên gọi: Khi phát hiện khả năng trùng lặp, người dùng có quyền tự quyết định tiếp tục tạo mới hay bắt buộc chuyển qua Admin duyệt?
4. **Chi trả thù lao Chuyên gia:** Việc giải ngân từ Quỹ dự án cho các chuyên gia có công nợ \`OPEN\` sẽ thực hiện tự động qua Smart Contract định kỳ hàng tuần, hay Admin ký duyệt chi thủ công từng khoản?
5. **Tiền tệ Tip & Quyên góp:** Ventlore hỗ trợ thanh toán tip và quyên góp bằng token ERC-20 (USDC) trên Arbitrum. Có cần mở rộng thêm native token (ETH) hay giải pháp thanh toán thẻ nội địa qua cổng trung gian không?
`;
