export interface DataMapRow {
  route: string;
  actor: string;
  component: string;
  fieldGroup: string;
  demoValue: string;
  currentSource: 'FE_STATIC' | 'FE_LOCAL_STATE' | 'BE_DYNAMIC' | 'WALLET_PUBLIC_READ' | 'CHAIN_VIA_BE' | string;
  targetSource: 'FE_STATIC' | 'FE_LOCAL_STATE' | 'BE_DYNAMIC' | 'WALLET_PUBLIC_READ' | 'CHAIN_VIA_BE' | string;
  inputId: string;
  outputId: string;
  viewers: string;
  modifiers: string;
  fetchTrigger: string;
  errorStates: string;
  clientState: string;
  cacheStrategy: string;
  decisionNeeded: string;
}

export const DATA_MAP_ROWS: DataMapRow[] = [
  {
    "route": "/ (Home)",
    "actor": "GUEST / ALL",
    "component": "HomePageView / Hero",
    "fieldGroup": "Tiêu đề, slogan, 2 nút CTA",
    "demoValue": "\"Hiểu nơi đến. Vững bước đi.\", Khám phá điểm đến, Tìm hiểu thêm",
    "currentSource": "FE_STATIC",
    "targetSource": "FE_STATIC",
    "inputId": "Không",
    "outputId": "Không",
    "viewers": "Công chúng (GUEST, USER)",
    "modifiers": "Admin (CMS)",
    "fetchTrigger": "Khi tải trang / đổi ngôn ngữ",
    "errorStates": "Fallback i18n chữ Việt",
    "clientState": "None",
    "cacheStrategy": "SSG / Prerender",
    "decisionNeeded": "Copywriting đã chốt 2 CTA chuẩn Single-Hero"
  },
  {
    "route": "/ (Home)",
    "actor": "GUEST / ALL",
    "component": "ContributeDialog",
    "fieldGroup": "4 hướng đóng góp: Điểm đã biết, Điểm mới, Thẩm định, Quỹ",
    "demoValue": "Viết bài điểm đã biết, Đề xuất điểm mới, Ứng tuyển thẩm định, Ủng hộ quỹ",
    "currentSource": "FE_STATIC",
    "targetSource": "FE_STATIC",
    "inputId": "Không",
    "outputId": "Không",
    "viewers": "Công chúng (GUEST, USER)",
    "modifiers": "Nội bộ FE",
    "fetchTrigger": "Khi mở modal",
    "errorStates": "None",
    "clientState": "Dialog Open state",
    "cacheStrategy": "Client component",
    "decisionNeeded": "4 luồng đóng góp độc lập theo Invariants"
  },
  {
    "route": "AppShell (All)",
    "actor": "ALL",
    "component": "AppShell / Nav",
    "fieldGroup": "Header brand, logo, search input, links",
    "demoValue": "Khám phá, Vùng dã ngoại, Minh bạch, Ủng hộ quỹ, Tài khoản",
    "currentSource": "FE_STATIC",
    "targetSource": "FE_STATIC",
    "inputId": "Không",
    "outputId": "Không",
    "viewers": "Công chúng (GUEST, USER)",
    "modifiers": "Nội bộ FE",
    "fetchTrigger": "Tải layout",
    "errorStates": "Hiển thị navbar rút gọn",
    "clientState": "Mobile drawer state",
    "cacheStrategy": "Prerender",
    "decisionNeeded": "Đã chuẩn hóa đa ngôn ngữ 6 locales"
  },
  {
    "route": "AppShell (All)",
    "actor": "ALL (Reviewer)",
    "component": "AppShell / PersonaSwitcher",
    "fieldGroup": "Chuyển đổi vai trò demo",
    "demoValue": "GUEST, USER (Member), USER (Author), USER (VIP), EXPERT, ADMIN",
    "currentSource": "FE_LOCAL_STATE",
    "targetSource": "FE_LOCAL_STATE",
    "inputId": "Không",
    "outputId": "userId duy nhất xuyên suốt",
    "viewers": "Reviewer / Dev",
    "modifiers": "User",
    "fetchTrigger": "Tức thì khi click",
    "errorStates": "Giữ nguyên persona",
    "clientState": "LocalStorage ventlore_persona",
    "cacheStrategy": "Client Only",
    "decisionNeeded": "Chỉ hiển thị ở môi trường Dev / Staging"
  },
  {
    "route": "AppShell (All)",
    "actor": "USER (Member+)",
    "component": "AppShell / UserMenu",
    "fieldGroup": "Menu hồ sơ & thông báo",
    "demoValue": "Avatar, Handle, Badge vai trò, Đóng góp của tôi, Quyền lợi, Thoát",
    "currentSource": "FE_LOCAL_STATE",
    "targetSource": "BE_DYNAMIC",
    "inputId": "userId",
    "outputId": "Tái dùng userId",
    "viewers": "User đăng nhập",
    "modifiers": "User",
    "fetchTrigger": "Khi session thay đổi",
    "errorStates": "Chế độ GUEST (Đăng nhập)",
    "clientState": "Cookie session",
    "cacheStrategy": "SSR / Client query",
    "decisionNeeded": "Đã bổ sung mục Quyền lợi vào menu người dùng"
  },
  {
    "route": "/explore",
    "actor": "ALL",
    "component": "SearchFilters",
    "fieldGroup": "Bộ lọc vùng, hoạt động, độ khó",
    "demoValue": "Miền núi phía Bắc, Ven biển; Trekking, Kayak",
    "currentSource": "FE_STATIC",
    "targetSource": "BE_DYNAMIC",
    "inputId": "Không",
    "outputId": "Tái dùng regionId",
    "viewers": "Công chúng",
    "modifiers": "ADMIN",
    "fetchTrigger": "Tải trang Explore",
    "errorStates": "Dropdown mặc định",
    "clientState": "URL SearchParams (?region=...)",
    "cacheStrategy": "Client state + query",
    "decisionNeeded": "Danh mục vùng có cần thêm cấp huyện/xã"
  },
  {
    "route": "/explore",
    "actor": "ALL",
    "component": "PlaceResults",
    "fieldGroup": "Lưới thẻ điểm đến, badges cảnh báo",
    "demoValue": "Ảnh, Tên, Vùng, Số bài, Nhãn an toàn",
    "currentSource": "FE_STATIC",
    "targetSource": "BE_DYNAMIC",
    "inputId": "Search filters",
    "outputId": "Tái dùng placeId (ACTIVE / REVIEW_ONLY)",
    "viewers": "Công chúng",
    "modifiers": "System",
    "fetchTrigger": "Khi thay đổi bộ lọc",
    "errorStates": "\"Không tìm thấy địa điểm phù hợp\"",
    "clientState": "URL query",
    "cacheStrategy": "Client cache / SWR",
    "decisionNeeded": "Phân trang bằng Infinite scroll hay Nút bấm"
  },
  {
    "route": "/explore",
    "actor": "ALL",
    "component": "PlaceMap",
    "fieldGroup": "Bản đồ tương tác Leaflet / Pins",
    "demoValue": "Tọa độ GPS, Markers, Popup card",
    "currentSource": "FE_STATIC",
    "targetSource": "BE_DYNAMIC",
    "inputId": "Bounding box",
    "outputId": "Tái dùng placeId",
    "viewers": "Công chúng",
    "modifiers": "System",
    "fetchTrigger": "Khi pan/zoom map",
    "errorStates": "Bản đồ xám, giữ pin cũ",
    "clientState": "Viewport lat/lng",
    "cacheStrategy": "Client Only (no SSR)",
    "decisionNeeded": "Nhà cung cấp bản đồ (OpenStreetMap vs Mapbox)"
  },
  {
    "route": "/places/[placeId]",
    "actor": "ALL",
    "component": "PlaceSummary",
    "fieldGroup": "Tên điểm, cảnh báo, tọa độ, mô tả",
    "demoValue": "Vịnh Cát Cò 3, Cảnh báo dòng chảy xiết ngầm",
    "currentSource": "FE_STATIC",
    "targetSource": "BE_DYNAMIC",
    "inputId": "placeId",
    "outputId": "Tái dùng placeId (ACTIVE / CANDIDATE)",
    "viewers": "Công chúng",
    "modifiers": "EXPERT / ADMIN",
    "fetchTrigger": "Khi vào trang điểm",
    "errorStates": "404 Place Not Found",
    "clientState": "None",
    "cacheStrategy": "SSG + ISR",
    "decisionNeeded": "Cảnh báo khẩn cấp có cần nút chia sẻ nhanh"
  },
  {
    "route": "/posts/[postId]",
    "actor": "ALL",
    "component": "PostReader",
    "fieldGroup": "Bài viết, tác giả, ngày quan sát",
    "demoValue": "Tiêu đề, Tác giả Minh, Ngày 15/06/2026, Nội dung MD",
    "currentSource": "FE_STATIC",
    "targetSource": "BE_DYNAMIC",
    "inputId": "postId, revisionId",
    "outputId": "Tái dùng postId, revisionId (Bất biến sau nộp)",
    "viewers": "Công chúng",
    "modifiers": "Tác giả gốc (authorUserId)",
    "fetchTrigger": "Khi vào xem bài",
    "errorStates": "Lỗi tải bài, nội dung ẩn",
    "clientState": "Active revision query",
    "cacheStrategy": "SSG + ISR",
    "decisionNeeded": "VIP content làm mờ (blur) hay cắt ngắn"
  },
  {
    "route": "/posts/[postId]",
    "actor": "ALL",
    "component": "VerificationPanel",
    "fieldGroup": "Huy hiệu kiểm định, phạm vi, hạn dùng",
    "demoValue": "VERIFIED, 15/06/2026 - 15/06/2027, Phạm vi an toàn",
    "currentSource": "FE_STATIC",
    "targetSource": "BE_DYNAMIC",
    "inputId": "revisionId",
    "outputId": "Tái dùng decisionId (Gắn theo revisionId và claimId)",
    "viewers": "Công chúng",
    "modifiers": "OPERATOR / ADMIN",
    "fetchTrigger": "Cùng với post",
    "errorStates": "UNVERIFIED, IN_REVIEW, NEEDS_CHANGES, EXPIRED, SUSPENDED",
    "clientState": "None",
    "cacheStrategy": "Prerender",
    "decisionNeeded": "Thể hiện trạng thái EXPIRED (Hết hạn) thế nào"
  },
  {
    "route": "/posts/[postId]",
    "actor": "ALL",
    "component": "PostReader / TipCTA",
    "fieldGroup": "Nút \"Tip tác giả\", tỷ lệ 80/20",
    "demoValue": "Nút Tip Author, mở PaymentModal POST_TIP",
    "currentSource": "FE_STATIC",
    "targetSource": "BE_DYNAMIC + CHAIN_VIA_BE",
    "inputId": "postId, revisionId",
    "outputId": "routeId (Kích hoạt khi bài APPROVED & tác giả ký đồng ý)",
    "viewers": "Công chúng",
    "modifiers": "Tác giả (consent) + OPERATOR",
    "fetchTrigger": "Khi render bài",
    "errorStates": "Nút mờ + Lý do chặn",
    "clientState": "Modal trigger",
    "cacheStrategy": "Client component",
    "decisionNeeded": "Tỷ lệ chia sẻ bất biến: 80% tác giả, 20% quỹ"
  },
  {
    "route": "/posts/[postId]",
    "actor": "USER (Đã đăng nhập)",
    "component": "ReportDialog",
    "fieldGroup": "Form báo cáo thông tin sai lệch",
    "demoValue": "Nhận định claim, lý do báo sai, link dẫn chứng",
    "currentSource": "FE_LOCAL_STATE",
    "targetSource": "BE_DYNAMIC",
    "inputId": "postId, claimId",
    "outputId": "Sinh reportId (UUIDv7)",
    "viewers": "Thành viên",
    "modifiers": "Thành viên báo",
    "fetchTrigger": "Khi bấm Báo sai",
    "errorStates": "Khóa nút khi đang gửi",
    "clientState": "Form state",
    "cacheStrategy": "Client Modal",
    "decisionNeeded": "Người dùng ẩn danh có được gửi report không"
  },
  {
    "route": "PaymentModal",
    "actor": "ALL",
    "component": "PaymentModal",
    "fieldGroup": "Khung thanh toán chung (3 modes)",
    "demoValue": "PROJECT, POST_TIP, MEMBERSHIP; Mạng Arbitrum",
    "currentSource": "FE_LOCAL_STATE",
    "targetSource": "WALLET_PUBLIC_READ + BE_DYNAMIC",
    "inputId": "Mode, targetId, Idempotency-Key",
    "outputId": "Sinh paymentIntentId (OFFCHAIN_INTENT -> OBSERVED -> CONFIRMED -> SETTLED)",
    "viewers": "Người thanh toán",
    "modifiers": "Người thanh toán",
    "fetchTrigger": "Khi bấm nút mở modal",
    "errorStates": "Sai mạng, thiếu gas, thiếu token",
    "clientState": "Context state",
    "cacheStrategy": "Client Modal",
    "decisionNeeded": "Hard invariant: Chặn hoàn toàn Guest mua VIP demo"
  },
  {
    "route": "PaymentModal",
    "actor": "ALL",
    "component": "PaymentModal / WalletConnect",
    "fieldGroup": "Trạng thái ví Web3 (Mô phỏng demo)",
    "demoValue": "0x71C...3aF8, Arbitrum One, Số dư 250 USDC (Mô phỏng demo)",
    "currentSource": "WALLET_PUBLIC_READ",
    "targetSource": "WALLET_PUBLIC_READ",
    "inputId": "Provider",
    "outputId": "Không",
    "viewers": "Người thanh toán",
    "modifiers": "User (đổi ví)",
    "fetchTrigger": "Khi kết nối ví",
    "errorStates": "\"Chưa kết nối ví\", \"Sai mạng\"",
    "clientState": "Injected provider",
    "cacheStrategy": "Client Only",
    "decisionNeeded": "Wallet kit ưu tiên (RainbowKit vs AppKit)"
  },
  {
    "route": "/vip",
    "actor": "ALL",
    "component": "VipPage / PricingCard",
    "fieldGroup": "Giá gói, kỳ hạn, danh sách đặc quyền",
    "demoValue": "15 USD / 12 tháng lịch UTC; Mở khóa báo cáo sâu",
    "currentSource": "FE_STATIC",
    "targetSource": "BE_DYNAMIC (Plan config)",
    "inputId": "planCode",
    "outputId": "Không",
    "viewers": "Công chúng",
    "modifiers": "ADMIN cấu hình",
    "fetchTrigger": "Tải trang VIP",
    "errorStates": "Giá mặc định $15 (1500 USD cents)",
    "clientState": "None",
    "cacheStrategy": "SSG / ISR",
    "decisionNeeded": "Giá cố định 1500 USD cents/năm, cộng nối tiếp 365 ngày nếu còn hạn"
  },
  {
    "route": "/vip",
    "actor": "USER (Member+)",
    "component": "VipPage / SubCTA",
    "fieldGroup": "Nút Đăng ký / Gia hạn gói VIP",
    "demoValue": "Mở PaymentModal MEMBERSHIP ($15)",
    "currentSource": "FE_LOCAL_STATE",
    "targetSource": "BE_DYNAMIC",
    "inputId": "userId, planCode",
    "outputId": "Sinh paymentIntentId -> membershipId (12 tháng UTC)",
    "viewers": "Hội viên",
    "modifiers": "Hội viên",
    "fetchTrigger": "Khi bấm mua/gia hạn",
    "errorStates": "Đăng nhập trước",
    "clientState": "Modal state",
    "cacheStrategy": "Client component",
    "decisionNeeded": "VIP gắn theo userId, gia hạn chủ động, không tự động trừ tiền"
  },
  {
    "route": "/contribute",
    "actor": "USER (Member+)",
    "component": "ContributeView / Tab1",
    "fieldGroup": "Form viết bài cho điểm có sẵn",
    "demoValue": "Chọn Place, Tiêu đề, Loại bài, Markdown, Claims",
    "currentSource": "FE_LOCAL_STATE",
    "targetSource": "BE_DYNAMIC",
    "inputId": "placeId (ACTIVE)",
    "outputId": "Sinh postId + revisionId (DRAFT -> SUBMITTED)",
    "viewers": "Tác giả",
    "modifiers": "Tác giả",
    "fetchTrigger": "Tải danh sách places",
    "errorStates": "Lỗi 409 xung đột phiên bản",
    "clientState": "LocalStorage draft_${userId}_existing, URL ?tab=existing",
    "cacheStrategy": "Client form",
    "decisionNeeded": "Cho phép lưu nháp trên server (BE Draft) không"
  },
  {
    "route": "/contribute",
    "actor": "USER (Member+)",
    "component": "ContributeView / Tab2",
    "fieldGroup": "Form đề xuất điểm mới",
    "demoValue": "Tên điểm, Vùng, Tọa độ GPS, Cảnh báo, Bài khám phá",
    "currentSource": "FE_LOCAL_STATE",
    "targetSource": "BE_DYNAMIC",
    "inputId": "regionId",
    "outputId": "Sinh placeId (CANDIDATE, REVIEW_ONLY) + postId (DISCOVERY) + revisionId trong 1 transaction",
    "viewers": "Tác giả",
    "modifiers": "Tác giả",
    "fetchTrigger": "Tức thì khi nhập",
    "errorStates": "Trùng lặp tiềm năng",
    "clientState": "LocalStorage draft_${userId}_candidate, URL ?tab=candidate",
    "cacheStrategy": "Client form",
    "decisionNeeded": "Đề xuất tạo đồng thời 3 thực thể, trạng thái REVIEW_ONLY trước khi duyệt"
  },
  {
    "route": "/contribute",
    "actor": "USER (Member+)",
    "component": "ContributeView / Duplicate",
    "fieldGroup": "Hộp cảnh báo điểm trùng lặp",
    "demoValue": "\"Phát hiện điểm tương tự: Vịnh Cát Cò 3 (85%)\"",
    "currentSource": "FE_LOCAL_STATE",
    "targetSource": "BE_DYNAMIC",
    "inputId": "Tên điểm gõ vào, Tọa độ GPS",
    "outputId": "Tái dùng placeId trùng",
    "viewers": "Tác giả",
    "modifiers": "System",
    "fetchTrigger": "Khi người dùng gõ tên",
    "errorStates": "None",
    "clientState": "Inline warning",
    "cacheStrategy": "Client check",
    "decisionNeeded": "Cho phép bỏ qua cảnh báo để tạo điểm mới"
  },
  {
    "route": "/account",
    "actor": "USER (Member+)",
    "component": "AccountView / Profile",
    "fieldGroup": "Hồ sơ cá nhân & userId duy nhất",
    "demoValue": "Tên, Handle, userId (UUIDv7), Vai trò hệ thống",
    "currentSource": "FE_LOCAL_STATE",
    "targetSource": "BE_DYNAMIC",
    "inputId": "userId",
    "outputId": "Tái dùng userId",
    "viewers": "User sở hữu",
    "modifiers": "User",
    "fetchTrigger": "Tải trang cá nhân",
    "errorStates": "Chưa đăng nhập -> redirect",
    "clientState": "Cookie session, URL ?tab=profile",
    "cacheStrategy": "SSR / Client query",
    "decisionNeeded": "Trường thông tin nào công khai ra ngoài"
  },
  {
    "route": "/account",
    "actor": "USER (Member+)",
    "component": "AccountView / Wallet",
    "fieldGroup": "Khung liên kết ví Web3 (Mô phỏng demo)",
    "demoValue": "0x71C...3aF8, Arbitrum Sepolia, Đã xác minh (Mô phỏng demo)",
    "currentSource": "WALLET_PUBLIC_READ",
    "targetSource": "BE_DYNAMIC + WALLET_PUBLIC_READ",
    "inputId": "userId, signature",
    "outputId": "Sinh walletBindingId độc lập trỏ về userId",
    "viewers": "User sở hữu",
    "modifiers": "User",
    "fetchTrigger": "Tải trang cá nhân",
    "errorStates": "\"Chưa liên kết ví Web3\"",
    "clientState": "None",
    "cacheStrategy": "Client query",
    "decisionNeeded": "Yêu cầu ký thông điệp SIWE khi liên kết ví"
  },
  {
    "route": "/account",
    "actor": "USER (Member+)",
    "component": "AccountView / MyContribs",
    "fieldGroup": "Danh sách bài & điểm đã nộp",
    "demoValue": "Mã PST, Trạng thái (UNVERIFIED, REVIEW_ONLY, APPROVED)",
    "currentSource": "FE_LOCAL_STATE",
    "targetSource": "BE_DYNAMIC",
    "inputId": "userId",
    "outputId": "Tái dùng postId",
    "viewers": "User sở hữu",
    "modifiers": "Tác giả",
    "fetchTrigger": "Tải tab đóng góp",
    "errorStates": "\"Chưa có bài đóng góp nào\"",
    "clientState": "URL ?tab=contributions",
    "cacheStrategy": "Client query",
    "decisionNeeded": "Có cho phép xóa bài đã gửi không (Invariant cấm)"
  },
  {
    "route": "/account",
    "actor": "USER (Member+)",
    "component": "AccountView / NewRevision",
    "fieldGroup": "Drawer nộp bản sửa đổi",
    "demoValue": "Tiêu đề mới, Ghi chú sửa đổi theo yêu cầu",
    "currentSource": "FE_LOCAL_STATE",
    "targetSource": "BE_DYNAMIC",
    "inputId": "postId, parentRevisionId",
    "outputId": "Sinh revisionId mới (v+1), không thừa hưởng nhãn cũ",
    "viewers": "Tác giả",
    "modifiers": "Tác giả",
    "fetchTrigger": "Khi bấm nộp sửa đổi",
    "errorStates": "Lỗi lưu bản ghi",
    "clientState": "Drawer form",
    "cacheStrategy": "Client modal",
    "decisionNeeded": "Phiên bản mới tạo revisionId mới, trỏ parentRevisionId"
  },
  {
    "route": "/account",
    "actor": "USER (Member+)",
    "component": "AccountView / VIPTab",
    "fieldGroup": "Tình trạng gói VIP & Nút gia hạn",
    "demoValue": "ACTIVE, Còn 280 ngày, Hạn 15/06/2027",
    "currentSource": "FE_LOCAL_STATE",
    "targetSource": "BE_DYNAMIC",
    "inputId": "userId",
    "outputId": "Tái dùng membershipId (Kỳ hạn 12 tháng UTC, cộng nối tiếp)",
    "viewers": "User sở hữu",
    "modifiers": "User",
    "fetchTrigger": "Tải tab VIP",
    "errorStates": "Hết hạn (EXPIRED)",
    "clientState": "URL ?tab=vip",
    "cacheStrategy": "Client query",
    "decisionNeeded": "Gia hạn chủ động 15 USD/năm, cộng dồn nối tiếp kỳ hiện tại"
  },
  {
    "route": "/account",
    "actor": "USER (Member+)",
    "component": "AccountView / Benefits",
    "fieldGroup": "Bốn khối quyền lợi sau duyệt",
    "demoValue": "1. Nhãn web; 2. SBT; 3. NFT (tối đa 1/post); 4. Tip Route 80/20",
    "currentSource": "FE_LOCAL_STATE",
    "targetSource": "CHAIN_VIA_BE + BE_DYNAMIC",
    "inputId": "userId",
    "outputId": "Tái dùng credentialId / collectibleId (tokenId = uint256(key))",
    "viewers": "Tác giả",
    "modifiers": "Tác giả",
    "fetchTrigger": "Tải tab quyền lợi",
    "errorStates": "Chưa đủ điều kiện (Not Eligible)",
    "clientState": "URL ?tab=benefits",
    "cacheStrategy": "Client query",
    "decisionNeeded": "4 quyền lợi kích hoạt độc lập khi bài viết được APPROVED"
  },
  {
    "route": "/expert",
    "actor": "EXPERT",
    "component": "ExpertWorkspaceView / Tasks",
    "fieldGroup": "Bảng việc thực địa (5 trạng thái)",
    "demoValue": "Offered, In Progress, Submitted, Accepted Work",
    "currentSource": "FE_LOCAL_STATE",
    "targetSource": "BE_DYNAMIC",
    "inputId": "expertUserId",
    "outputId": "Tái dùng taskId",
    "viewers": "Chuyên gia",
    "modifiers": "Chuyên gia",
    "fetchTrigger": "Tải trang Expert",
    "errorStates": "\"Không có nhiệm vụ nào\"",
    "clientState": "Subfilter state",
    "cacheStrategy": "Client query",
    "decisionNeeded": "Hạn chót từ chối nhận việc (bao nhiêu giờ)"
  },
  {
    "route": "/expert",
    "actor": "EXPERT",
    "component": "ExpertWorkspaceView / Evidence",
    "fieldGroup": "Modal nộp bằng chứng & đánh giá claims",
    "demoValue": "Khảo sát từng claim (Đúng/Sai), Kết luận, Bằng chứng",
    "currentSource": "FE_LOCAL_STATE",
    "targetSource": "BE_DYNAMIC",
    "inputId": "taskId",
    "outputId": "Sinh submissionId (Bất biến sau khi nộp)",
    "viewers": "Chuyên gia",
    "modifiers": "Chuyên gia",
    "fetchTrigger": "Khi bấm nộp báo cáo",
    "errorStates": "Khóa nút khi gửi",
    "clientState": "Form modal",
    "cacheStrategy": "Client modal",
    "decisionNeeded": "Định dạng tệp ảnh đối chứng (JPEG/GPX tracklog)"
  },
  {
    "route": "/expert",
    "actor": "EXPERT",
    "component": "ExpertWorkspaceView / Payables",
    "fieldGroup": "Bảng công phải nhận",
    "demoValue": "Mã công nợ, Thù lao (50 USDC), OPEN, PAID",
    "currentSource": "FE_LOCAL_STATE",
    "targetSource": "CHAIN_VIA_BE + BE_DYNAMIC",
    "inputId": "expertUserId",
    "outputId": "Sinh payableId (truy xuất từ acceptanceId, độc lập với decisionId)",
    "viewers": "Chuyên gia",
    "modifiers": "Ban điều hành",
    "fetchTrigger": "Tải tab payables",
    "errorStates": "\"Chưa có công nợ nào\"",
    "clientState": "Tab state",
    "cacheStrategy": "Client query",
    "decisionNeeded": "Chuyên gia làm đúng quy trình vẫn nhận tiền công dù bài REJECTED"
  },
  {
    "route": "/admin",
    "actor": "ADMIN / OPERATOR",
    "component": "AdminWorkspaceView / Intake",
    "fieldGroup": "Tiếp nhận hồ sơ & khiếu nại",
    "demoValue": "Danh sách candidate places, bài viết mới, báo sai",
    "currentSource": "FE_LOCAL_STATE",
    "targetSource": "BE_DYNAMIC",
    "inputId": "Không",
    "outputId": "Tái dùng intakeId / reviewCaseId",
    "viewers": "Ban điều hành",
    "modifiers": "Ban điều hành",
    "fetchTrigger": "Tải trang Admin",
    "errorStates": "Hàng đợi trống",
    "clientState": "Tab state",
    "cacheStrategy": "Client query",
    "decisionNeeded": "Quy trình tự động phân luồng theo vùng địa lý"
  },
  {
    "route": "/admin",
    "actor": "ADMIN / OPERATOR",
    "component": "AdminWorkspaceView / Compare",
    "fieldGroup": "Popup đối chiếu điểm trùng",
    "demoValue": "So sánh Tên, Vùng, Tọa độ giữa bài nộp và hệ thống",
    "currentSource": "FE_LOCAL_STATE",
    "targetSource": "BE_DYNAMIC",
    "inputId": "intakeId, placeId",
    "outputId": "Không",
    "viewers": "Ban điều hành",
    "modifiers": "Ban điều hành",
    "fetchTrigger": "Khi bấm So sánh",
    "errorStates": "Không có điểm trùng",
    "clientState": "Modal state",
    "cacheStrategy": "Client modal",
    "decisionNeeded": "Quyền gộp điểm thuộc Admin hay Chuyên gia"
  },
  {
    "route": "/admin",
    "actor": "ADMIN / OPERATOR",
    "component": "AdminWorkspaceView / Assign",
    "fieldGroup": "Modal giao việc cho chuyên gia",
    "demoValue": "Chọn Chuyên gia Hoàng, Hạn 7 ngày, Thù lao 50 USDC",
    "currentSource": "FE_LOCAL_STATE",
    "targetSource": "BE_DYNAMIC",
    "inputId": "reviewCaseId (cặp revisionId + scopeClaimIds)",
    "outputId": "Sinh taskId giao cho chuyên gia độc lập",
    "viewers": "Ban điều hành",
    "modifiers": "Ban điều hành",
    "fetchTrigger": "Khi bấm Giao việc",
    "errorStates": "Không có chuyên gia rảnh",
    "clientState": "Form modal",
    "cacheStrategy": "Client modal",
    "decisionNeeded": "Không tự kiểm định bài viết của chính mình"
  },
  {
    "route": "/admin",
    "actor": "ADMIN / OPERATOR",
    "component": "AdminWorkspaceView / WorkAccept",
    "fieldGroup": "Nghiệm thu chất lượng công việc (QĐ 1)",
    "demoValue": "ACCEPTED_WORK hoặc REJECTED_WORK kèm lý do",
    "currentSource": "FE_LOCAL_STATE",
    "targetSource": "BE_DYNAMIC",
    "inputId": "taskId, submissionId",
    "outputId": "Quyết định 1: Sinh acceptanceId -> payableId",
    "viewers": "Ban điều hành",
    "modifiers": "Ban điều hành",
    "fetchTrigger": "Khi xem submission",
    "errorStates": "Ghi nhận thất bại",
    "clientState": "Modal state",
    "cacheStrategy": "Client modal",
    "decisionNeeded": "Quyết định 1: Đánh giá chất lượng thực hiện công việc chuyên gia"
  },
  {
    "route": "/admin",
    "actor": "ADMIN / OPERATOR",
    "component": "AdminWorkspaceView / ContentDecide",
    "fieldGroup": "Quyết định nội dung bài viết (QĐ 2)",
    "demoValue": "APPROVED, REJECTED, CHANGES_REQUESTED",
    "currentSource": "FE_LOCAL_STATE",
    "targetSource": "BE_DYNAMIC",
    "inputId": "reviewCaseId",
    "outputId": "Quyết định 2: Sinh decisionId",
    "viewers": "Ban điều hành",
    "modifiers": "Ban điều hành",
    "fetchTrigger": "Sau khi chuyên gia nộp",
    "errorStates": "Ghi nhận quyết định",
    "clientState": "Modal state",
    "cacheStrategy": "Client modal",
    "decisionNeeded": "Quyết định 2: Kết luận tính chính xác của nội dung bài viết"
  },
  {
    "route": "/admin",
    "actor": "ADMIN / OPERATOR",
    "component": "AdminWorkspaceView / Hold",
    "fieldGroup": "Bật / Tắt App Hold khẩn cấp",
    "demoValue": "Khóa luồng tip và gắn cờ cảnh báo trên UI",
    "currentSource": "FE_LOCAL_STATE",
    "targetSource": "BE_DYNAMIC + CHAIN_VIA_BE",
    "inputId": "revisionId",
    "outputId": "Cập nhật cờ hold / SUSPENDED",
    "viewers": "Ban điều hành",
    "modifiers": "Ban điều hành",
    "fetchTrigger": "Khi bấm nút Hold",
    "errorStates": "Thất bại kết nối",
    "clientState": "Switch state",
    "cacheStrategy": "Client action",
    "decisionNeeded": "Thời gian tối đa giữ trạng thái App Hold"
  },
  {
    "route": "/transparency",
    "actor": "ALL",
    "component": "PublicLedger",
    "fieldGroup": "Sổ cái công khai số dư quỹ & nguồn thu",
    "demoValue": "45.200 USDC, 3.4 ETH; Quỹ dự án, Phí hội viên",
    "currentSource": "FE_STATIC",
    "targetSource": "CHAIN_VIA_BE + BE_DYNAMIC",
    "inputId": "Không",
    "outputId": "Không",
    "viewers": "Công chúng",
    "modifiers": "System",
    "fetchTrigger": "Tải trang Minh bạch",
    "errorStates": "Bảng rỗng",
    "clientState": "Year selector",
    "cacheStrategy": "SSG + ISR (1h)",
    "decisionNeeded": "Tần suất worker đồng bộ số dư onchain"
  },
  {
    "route": "/transparency",
    "actor": "ALL",
    "component": "PublicLedger / Stream",
    "fieldGroup": "Nhật ký giao dịch mô phỏng live",
    "demoValue": "Danh sách đơn thanh toán: POST_TIP, PROJECT, MEMBERSHIP",
    "currentSource": "FE_LOCAL_STATE",
    "targetSource": "CHAIN_VIA_BE + BE_DYNAMIC",
    "inputId": "Không",
    "outputId": "Tái dùng paymentIntentId / receiptKey",
    "viewers": "Công chúng",
    "modifiers": "System",
    "fetchTrigger": "Polling 3s một lần",
    "errorStates": "\"Chưa có giao dịch nào\"",
    "clientState": "Polling state",
    "cacheStrategy": "Client live query",
    "decisionNeeded": "Giới hạn số dòng hiển thị công khai (20 hay 50)"
  },
  {
    "route": "Floating",
    "actor": "ALL (Reviewer)",
    "component": "ReviewToolbar",
    "fieldGroup": "Khung điều khiển nghiệm thu 14 kịch bản",
    "demoValue": "14 kịch bản, 5 personas, Bottom-left dock",
    "currentSource": "FE_LOCAL_STATE",
    "targetSource": "FE_LOCAL_STATE",
    "inputId": "Không",
    "outputId": "Không",
    "viewers": "Bin / QA Reviewer",
    "modifiers": "Reviewer",
    "fetchTrigger": "Tải mọi trang",
    "errorStates": "Thu gọn thành icon pill",
    "clientState": "Widget Open state",
    "cacheStrategy": "Client Only",
    "decisionNeeded": "Công cụ hỗ trợ Bin nghiệm thu 14 kịch bản; đặt góc dưới bên trái"
  }
];

export const KEY_DECISIONS = [
  {
    number: 1,
    title: 'Lưu trữ bản nháp (Draft persistence)',
    description: 'Hiện tại nháp bài viết và địa điểm mới lưu tại localStorage của trình duyệt người dùng. Sau này có cần hỗ trợ đồng bộ nháp lên máy chủ (BE Draft) khi tác giả đổi máy tính hoặc điện thoại không?',
    recommendation: 'Đề xuất hỗ trợ LocalStorage trước trong MVP; lưu BE draft ở phiên bản tiếp theo khi người dùng bấm Lưu nháp có chủ đích.',
  },
  {
    number: 2,
    title: 'Quyền truy cập nội dung VIP (VIP Content Access)',
    description: 'Mức độ hiển thị nội dung VIP đối với Guest và Member thường: Làm mờ các đoạn văn cảnh báo chuyên sâu (blur) hay chỉ hiển thị tóm tắt và ẩn hoàn toàn phần nhận định chi tiết?',
    recommendation: 'Đề xuất làm mờ kèm nút Mở khóa VIP để tăng tỷ lệ chuyển đổi hội viên và kích thích tò mò.',
  },
  {
    number: 3,
    title: 'Cảnh báo điểm trùng lặp (Duplicate Place Threshold)',
    description: 'Ngưỡng khoảng cách GPS (ví dụ 100m hay 500m) và độ tương đồng tên gọi: Khi phát hiện khả năng trùng lặp, người dùng có quyền tự quyết định tiếp tục tạo mới hay bắt buộc chuyển qua Admin duyệt?',
    recommendation: 'Cảnh báo màu cam và gợi ý chuyển sang viết bài cho điểm có sẵn, nhưng cho phép tiếp tục nếu người dùng xác nhận đây là điểm riêng biệt.',
  },
  {
    number: 4,
    title: 'Chi trả thù lao Chuyên gia (Expert Payables Release)',
    description: 'Việc giải ngân từ Quỹ dự án cho các chuyên gia có công nợ OPEN sẽ thực hiện tự động qua Smart Contract định kỳ hàng tuần, hay Admin ký duyệt chi thủ công từng khoản?',
    recommendation: 'Admin ký lệnh duyệt chi theo đợt (Batch Payout) để tối ưu chi phí gas trên mạng Arbitrum.',
  },
  {
    number: 5,
    title: 'Tiền tệ Tip & Quyên góp (Tip & Donation Currencies)',
    description: 'Ventlore hỗ trợ thanh toán tip và quyên góp bằng token ERC-20 (USDC) trên Arbitrum. Có cần mở rộng thêm native token (ETH) hay giải pháp thanh toán thẻ nội địa qua cổng trung gian không?',
    recommendation: 'Khởi đầu với USDC trên Arbitrum One vì giá trị ổn định 1:1 USD, phí gas siêu rẻ (< 0.05 USD).',
  },
];

export const RAW_FE_DATA_MAP_MD = "# Ventlore · FE Data Map (Bản Đồ Quyết Định Dữ Liệu Tĩnh / Động v1.2)\n\nTài liệu này xác lập chi tiết từng component và 38 nhóm trường dữ liệu trên toàn bộ giao diện Front-End Ventlore sau đợt cập nhật v1.2 (26/09/2026). Đây là cơ sở cốt lõi để Đội ngũ Kỹ thuật đối chiếu và phát triển Backend (BE), Database, Indexer và Smart Contract sau khi Chủ dự án (Bin) nghiệm thu giao diện.\n\n---\n\n## 1. Phân loại Nguồn Đích (Target Data Sources)\n\n- `FE_STATIC`: Dữ liệu tĩnh, bản dịch i18n, copywriting, brand assets, constants cục bộ.\n- `FE_LOCAL_STATE`: Trạng thái tương tác tạm thời của người dùng trên trình duyệt (URL query, form input nháp, tab đang chọn, filter, trạng thái mở modal).\n- `BE_DYNAMIC`: Dữ liệu nghiệp vụ động lưu tại cơ sở dữ liệu PostgreSQL và trả về qua REST API (`/api/v1`).\n- `WALLET_PUBLIC_READ`: Dữ liệu công khai đọc trực tiếp từ Web3 Provider / RPC (Địa chỉ ví đang kết nối, Chain ID, số dư token ERC-20/ETH, allowance).\n- `CHAIN_VIA_BE`: Dữ liệu onchain (Smart Contract events, Splitter receipt, SBT/NFT mint transaction) đã được Indexer/Worker quét, giải mã và trả về qua API tổng hợp có thẩm quyền.\n\n---\n\n## 2. Bảng Ma Trận Dữ Liệu Chi Tiết (16 Cột Chuẩn Hóa — 38 Thành Phần Thực Tế)\n\n| Page/route | Actor | Component | Field/data group | Giá trị demo | Nguồn đang dùng | Nguồn đích đề xuất | ID đầu vào | ID tạo/sử dụng lại | Ai xem | Ai sửa | Khi nào tải/làm mới | Trạng thái lỗi/rỗng/chờ | Client state/persist | Gợi ý cache/render | Quyết định cần Bin chốt |\n| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |\n| `/ (Home)` | GUEST / ALL | `HomePageView / Hero` | Tiêu đề, slogan, 2 nút CTA | \"Hiểu nơi đến. Vững bước đi.\", Khám phá điểm đến, Tìm hiểu thêm | `FE_STATIC` | `FE_STATIC` | Không | Không | Công chúng (GUEST, USER) | Admin (CMS) | Khi tải trang / đổi ngôn ngữ | Fallback i18n chữ Việt | None | SSG / Prerender | Copywriting đã chốt 2 CTA chuẩn Single-Hero |\n| `/ (Home)` | GUEST / ALL | `ContributeDialog` | 4 hướng đóng góp: Điểm đã biết, Điểm mới, Thẩm định, Quỹ | Viết bài điểm đã biết, Đề xuất điểm mới, Ứng tuyển thẩm định, Ủng hộ quỹ | `FE_STATIC` | `FE_STATIC` | Không | Không | Công chúng (GUEST, USER) | Nội bộ FE | Khi mở modal | None | Dialog Open state | Client component | 4 luồng đóng góp độc lập theo Invariants |\n| `AppShell (All)` | ALL | `AppShell / Nav` | Header brand, logo, search input, links | Khám phá, Vùng dã ngoại, Minh bạch, Ủng hộ quỹ, Tài khoản | `FE_STATIC` | `FE_STATIC` | Không | Không | Công chúng (GUEST, USER) | Nội bộ FE | Tải layout | Hiển thị navbar rút gọn | Mobile drawer state | Prerender | Đã chuẩn hóa đa ngôn ngữ 6 locales |\n| `AppShell (All)` | ALL (Reviewer) | `AppShell / PersonaSwitcher` | Chuyển đổi vai trò demo | GUEST, USER (Member), USER (Author), USER (VIP), EXPERT, ADMIN | `FE_LOCAL_STATE` | `FE_LOCAL_STATE` | Không | userId duy nhất xuyên suốt | Reviewer / Dev | User | Tức thì khi click | Giữ nguyên persona | LocalStorage ventlore_persona | Client Only | Chỉ hiển thị ở môi trường Dev / Staging |\n| `AppShell (All)` | USER (Member+) | `AppShell / UserMenu` | Menu hồ sơ & thông báo | Avatar, Handle, Badge vai trò, Đóng góp của tôi, Quyền lợi, Thoát | `FE_LOCAL_STATE` | `BE_DYNAMIC` | userId | Tái dùng userId | User đăng nhập | User | Khi session thay đổi | Chế độ GUEST (Đăng nhập) | Cookie session | SSR / Client query | Đã bổ sung mục Quyền lợi vào menu người dùng |\n| `/explore` | ALL | `SearchFilters` | Bộ lọc vùng, hoạt động, độ khó | Miền núi phía Bắc, Ven biển; Trekking, Kayak | `FE_STATIC` | `BE_DYNAMIC` | Không | Tái dùng regionId | Công chúng | ADMIN | Tải trang Explore | Dropdown mặc định | URL SearchParams (?region=...) | Client state + query | Danh mục vùng có cần thêm cấp huyện/xã |\n| `/explore` | ALL | `PlaceResults` | Lưới thẻ điểm đến, badges cảnh báo | Ảnh, Tên, Vùng, Số bài, Nhãn an toàn | `FE_STATIC` | `BE_DYNAMIC` | Search filters | Tái dùng placeId (ACTIVE / REVIEW_ONLY) | Công chúng | System | Khi thay đổi bộ lọc | \"Không tìm thấy địa điểm phù hợp\" | URL query | Client cache / SWR | Phân trang bằng Infinite scroll hay Nút bấm |\n| `/explore` | ALL | `PlaceMap` | Bản đồ tương tác Leaflet / Pins | Tọa độ GPS, Markers, Popup card | `FE_STATIC` | `BE_DYNAMIC` | Bounding box | Tái dùng placeId | Công chúng | System | Khi pan/zoom map | Bản đồ xám, giữ pin cũ | Viewport lat/lng | Client Only (no SSR) | Nhà cung cấp bản đồ (OpenStreetMap vs Mapbox) |\n| `/places/[placeId]` | ALL | `PlaceSummary` | Tên điểm, cảnh báo, tọa độ, mô tả | Vịnh Cát Cò 3, Cảnh báo dòng chảy xiết ngầm | `FE_STATIC` | `BE_DYNAMIC` | placeId | Tái dùng placeId (ACTIVE / CANDIDATE) | Công chúng | EXPERT / ADMIN | Khi vào trang điểm | 404 Place Not Found | None | SSG + ISR | Cảnh báo khẩn cấp có cần nút chia sẻ nhanh |\n| `/posts/[postId]` | ALL | `PostReader` | Bài viết, tác giả, ngày quan sát | Tiêu đề, Tác giả Minh, Ngày 15/06/2026, Nội dung MD | `FE_STATIC` | `BE_DYNAMIC` | postId, revisionId | Tái dùng postId, revisionId (Bất biến sau nộp) | Công chúng | Tác giả gốc (authorUserId) | Khi vào xem bài | Lỗi tải bài, nội dung ẩn | Active revision query | SSG + ISR | VIP content làm mờ (blur) hay cắt ngắn |\n| `/posts/[postId]` | ALL | `VerificationPanel` | Huy hiệu kiểm định, phạm vi, hạn dùng | VERIFIED, 15/06/2026 - 15/06/2027, Phạm vi an toàn | `FE_STATIC` | `BE_DYNAMIC` | revisionId | Tái dùng decisionId (Gắn theo revisionId và claimId) | Công chúng | OPERATOR / ADMIN | Cùng với post | UNVERIFIED, IN_REVIEW, NEEDS_CHANGES, EXPIRED, SUSPENDED | None | Prerender | Thể hiện trạng thái EXPIRED (Hết hạn) thế nào |\n| `/posts/[postId]` | ALL | `PostReader / TipCTA` | Nút \"Tip tác giả\", tỷ lệ 80/20 | Nút Tip Author, mở PaymentModal POST_TIP | `FE_STATIC` | `BE_DYNAMIC + CHAIN_VIA_BE` | postId, revisionId | routeId (Kích hoạt khi bài APPROVED & tác giả ký đồng ý) | Công chúng | Tác giả (consent) + OPERATOR | Khi render bài | Nút mờ + Lý do chặn | Modal trigger | Client component | Tỷ lệ chia sẻ bất biến: 80% tác giả, 20% quỹ |\n| `/posts/[postId]` | USER (Đã đăng nhập) | `ReportDialog` | Form báo cáo thông tin sai lệch | Nhận định claim, lý do báo sai, link dẫn chứng | `FE_LOCAL_STATE` | `BE_DYNAMIC` | postId, claimId | Sinh reportId (UUIDv7) | Thành viên | Thành viên báo | Khi bấm Báo sai | Khóa nút khi đang gửi | Form state | Client Modal | Người dùng ẩn danh có được gửi report không |\n| `PaymentModal` | ALL | `PaymentModal` | Khung thanh toán chung (3 modes) | PROJECT, POST_TIP, MEMBERSHIP; Mạng Arbitrum | `FE_LOCAL_STATE` | `WALLET_PUBLIC_READ + BE_DYNAMIC` | Mode, targetId, Idempotency-Key | Sinh paymentIntentId (OFFCHAIN_INTENT -> OBSERVED -> CONFIRMED -> SETTLED) | Người thanh toán | Người thanh toán | Khi bấm nút mở modal | Sai mạng, thiếu gas, thiếu token | Context state | Client Modal | Hard invariant: Chặn hoàn toàn Guest mua VIP demo |\n| `PaymentModal` | ALL | `PaymentModal / WalletConnect` | Trạng thái ví Web3 (Mô phỏng demo) | 0x71C...3aF8, Arbitrum One, Số dư 250 USDC (Mô phỏng demo) | `WALLET_PUBLIC_READ` | `WALLET_PUBLIC_READ` | Provider | Không | Người thanh toán | User (đổi ví) | Khi kết nối ví | \"Chưa kết nối ví\", \"Sai mạng\" | Injected provider | Client Only | Wallet kit ưu tiên (RainbowKit vs AppKit) |\n| `/vip` | ALL | `VipPage / PricingCard` | Giá gói, kỳ hạn, danh sách đặc quyền | 15 USD / 12 tháng lịch UTC; Mở khóa báo cáo sâu | `FE_STATIC` | `BE_DYNAMIC (Plan config)` | planCode | Không | Công chúng | ADMIN cấu hình | Tải trang VIP | Giá mặc định $15 (1500 USD cents) | None | SSG / ISR | Giá cố định 1500 USD cents/năm, cộng nối tiếp 365 ngày nếu còn hạn |\n| `/vip` | USER (Member+) | `VipPage / SubCTA` | Nút Đăng ký / Gia hạn gói VIP | Mở PaymentModal MEMBERSHIP ($15) | `FE_LOCAL_STATE` | `BE_DYNAMIC` | userId, planCode | Sinh paymentIntentId -> membershipId (12 tháng UTC) | Hội viên | Hội viên | Khi bấm mua/gia hạn | Đăng nhập trước | Modal state | Client component | VIP gắn theo userId, gia hạn chủ động, không tự động trừ tiền |\n| `/contribute` | USER (Member+) | `ContributeView / Tab1` | Form viết bài cho điểm có sẵn | Chọn Place, Tiêu đề, Loại bài, Markdown, Claims | `FE_LOCAL_STATE` | `BE_DYNAMIC` | placeId (ACTIVE) | Sinh postId + revisionId (DRAFT -> SUBMITTED) | Tác giả | Tác giả | Tải danh sách places | Lỗi 409 xung đột phiên bản | LocalStorage draft_${userId}_existing, URL ?tab=existing | Client form | Cho phép lưu nháp trên server (BE Draft) không |\n| `/contribute` | USER (Member+) | `ContributeView / Tab2` | Form đề xuất điểm mới | Tên điểm, Vùng, Tọa độ GPS, Cảnh báo, Bài khám phá | `FE_LOCAL_STATE` | `BE_DYNAMIC` | regionId | Sinh placeId (CANDIDATE, REVIEW_ONLY) + postId (DISCOVERY) + revisionId trong 1 transaction | Tác giả | Tác giả | Tức thì khi nhập | Trùng lặp tiềm năng | LocalStorage draft_${userId}_candidate, URL ?tab=candidate | Client form | Đề xuất tạo đồng thời 3 thực thể, trạng thái REVIEW_ONLY trước khi duyệt |\n| `/contribute` | USER (Member+) | `ContributeView / Duplicate` | Hộp cảnh báo điểm trùng lặp | \"Phát hiện điểm tương tự: Vịnh Cát Cò 3 (85%)\" | `FE_LOCAL_STATE` | `BE_DYNAMIC` | Tên điểm gõ vào, Tọa độ GPS | Tái dùng placeId trùng | Tác giả | System | Khi người dùng gõ tên | None | Inline warning | Client check | Cho phép bỏ qua cảnh báo để tạo điểm mới |\n| `/account` | USER (Member+) | `AccountView / Profile` | Hồ sơ cá nhân & userId duy nhất | Tên, Handle, userId (UUIDv7), Vai trò hệ thống | `FE_LOCAL_STATE` | `BE_DYNAMIC` | userId | Tái dùng userId | User sở hữu | User | Tải trang cá nhân | Chưa đăng nhập -> redirect | Cookie session, URL ?tab=profile | SSR / Client query | Trường thông tin nào công khai ra ngoài |\n| `/account` | USER (Member+) | `AccountView / Wallet` | Khung liên kết ví Web3 (Mô phỏng demo) | 0x71C...3aF8, Arbitrum Sepolia, Đã xác minh (Mô phỏng demo) | `WALLET_PUBLIC_READ` | `BE_DYNAMIC + WALLET_PUBLIC_READ` | userId, signature | Sinh walletBindingId độc lập trỏ về userId | User sở hữu | User | Tải trang cá nhân | \"Chưa liên kết ví Web3\" | None | Client query | Yêu cầu ký thông điệp SIWE khi liên kết ví |\n| `/account` | USER (Member+) | `AccountView / MyContribs` | Danh sách bài & điểm đã nộp | Mã PST, Trạng thái (UNVERIFIED, REVIEW_ONLY, APPROVED) | `FE_LOCAL_STATE` | `BE_DYNAMIC` | userId | Tái dùng postId | User sở hữu | Tác giả | Tải tab đóng góp | \"Chưa có bài đóng góp nào\" | URL ?tab=contributions | Client query | Có cho phép xóa bài đã gửi không (Invariant cấm) |\n| `/account` | USER (Member+) | `AccountView / NewRevision` | Drawer nộp bản sửa đổi | Tiêu đề mới, Ghi chú sửa đổi theo yêu cầu | `FE_LOCAL_STATE` | `BE_DYNAMIC` | postId, parentRevisionId | Sinh revisionId mới (v+1), không thừa hưởng nhãn cũ | Tác giả | Tác giả | Khi bấm nộp sửa đổi | Lỗi lưu bản ghi | Drawer form | Client modal | Phiên bản mới tạo revisionId mới, trỏ parentRevisionId |\n| `/account` | USER (Member+) | `AccountView / VIPTab` | Tình trạng gói VIP & Nút gia hạn | ACTIVE, Còn 280 ngày, Hạn 15/06/2027 | `FE_LOCAL_STATE` | `BE_DYNAMIC` | userId | Tái dùng membershipId (Kỳ hạn 12 tháng UTC, cộng nối tiếp) | User sở hữu | User | Tải tab VIP | Hết hạn (EXPIRED) | URL ?tab=vip | Client query | Gia hạn chủ động 15 USD/năm, cộng dồn nối tiếp kỳ hiện tại |\n| `/account` | USER (Member+) | `AccountView / Benefits` | Bốn khối quyền lợi sau duyệt | 1. Nhãn web; 2. SBT; 3. NFT (tối đa 1/post); 4. Tip Route 80/20 | `FE_LOCAL_STATE` | `CHAIN_VIA_BE + BE_DYNAMIC` | userId | Tái dùng credentialId / collectibleId (tokenId = uint256(key)) | Tác giả | Tác giả | Tải tab quyền lợi | Chưa đủ điều kiện (Not Eligible) | URL ?tab=benefits | Client query | 4 quyền lợi kích hoạt độc lập khi bài viết được APPROVED |\n| `/expert` | EXPERT | `ExpertWorkspaceView / Tasks` | Bảng việc thực địa (5 trạng thái) | Offered, In Progress, Submitted, Accepted Work | `FE_LOCAL_STATE` | `BE_DYNAMIC` | expertUserId | Tái dùng taskId | Chuyên gia | Chuyên gia | Tải trang Expert | \"Không có nhiệm vụ nào\" | Subfilter state | Client query | Hạn chót từ chối nhận việc (bao nhiêu giờ) |\n| `/expert` | EXPERT | `ExpertWorkspaceView / Evidence` | Modal nộp bằng chứng & đánh giá claims | Khảo sát từng claim (Đúng/Sai), Kết luận, Bằng chứng | `FE_LOCAL_STATE` | `BE_DYNAMIC` | taskId | Sinh submissionId (Bất biến sau khi nộp) | Chuyên gia | Chuyên gia | Khi bấm nộp báo cáo | Khóa nút khi gửi | Form modal | Client modal | Định dạng tệp ảnh đối chứng (JPEG/GPX tracklog) |\n| `/expert` | EXPERT | `ExpertWorkspaceView / Payables` | Bảng công phải nhận | Mã công nợ, Thù lao (50 USDC), OPEN, PAID | `FE_LOCAL_STATE` | `CHAIN_VIA_BE + BE_DYNAMIC` | expertUserId | Sinh payableId (truy xuất từ acceptanceId, độc lập với decisionId) | Chuyên gia | Ban điều hành | Tải tab payables | \"Chưa có công nợ nào\" | Tab state | Client query | Chuyên gia làm đúng quy trình vẫn nhận tiền công dù bài REJECTED |\n| `/admin` | ADMIN / OPERATOR | `AdminWorkspaceView / Intake` | Tiếp nhận hồ sơ & khiếu nại | Danh sách candidate places, bài viết mới, báo sai | `FE_LOCAL_STATE` | `BE_DYNAMIC` | Không | Tái dùng intakeId / reviewCaseId | Ban điều hành | Ban điều hành | Tải trang Admin | Hàng đợi trống | Tab state | Client query | Quy trình tự động phân luồng theo vùng địa lý |\n| `/admin` | ADMIN / OPERATOR | `AdminWorkspaceView / Compare` | Popup đối chiếu điểm trùng | So sánh Tên, Vùng, Tọa độ giữa bài nộp và hệ thống | `FE_LOCAL_STATE` | `BE_DYNAMIC` | intakeId, placeId | Không | Ban điều hành | Ban điều hành | Khi bấm So sánh | Không có điểm trùng | Modal state | Client modal | Quyền gộp điểm thuộc Admin hay Chuyên gia |\n| `/admin` | ADMIN / OPERATOR | `AdminWorkspaceView / Assign` | Modal giao việc cho chuyên gia | Chọn Chuyên gia Hoàng, Hạn 7 ngày, Thù lao 50 USDC | `FE_LOCAL_STATE` | `BE_DYNAMIC` | reviewCaseId (cặp revisionId + scopeClaimIds) | Sinh taskId giao cho chuyên gia độc lập | Ban điều hành | Ban điều hành | Khi bấm Giao việc | Không có chuyên gia rảnh | Form modal | Client modal | Không tự kiểm định bài viết của chính mình |\n| `/admin` | ADMIN / OPERATOR | `AdminWorkspaceView / WorkAccept` | Nghiệm thu chất lượng công việc (QĐ 1) | ACCEPTED_WORK hoặc REJECTED_WORK kèm lý do | `FE_LOCAL_STATE` | `BE_DYNAMIC` | taskId, submissionId | Quyết định 1: Sinh acceptanceId -> payableId | Ban điều hành | Ban điều hành | Khi xem submission | Ghi nhận thất bại | Modal state | Client modal | Quyết định 1: Đánh giá chất lượng thực hiện công việc chuyên gia |\n| `/admin` | ADMIN / OPERATOR | `AdminWorkspaceView / ContentDecide` | Quyết định nội dung bài viết (QĐ 2) | APPROVED, REJECTED, CHANGES_REQUESTED | `FE_LOCAL_STATE` | `BE_DYNAMIC` | reviewCaseId | Quyết định 2: Sinh decisionId | Ban điều hành | Ban điều hành | Sau khi chuyên gia nộp | Ghi nhận quyết định | Modal state | Client modal | Quyết định 2: Kết luận tính chính xác của nội dung bài viết |\n| `/admin` | ADMIN / OPERATOR | `AdminWorkspaceView / Hold` | Bật / Tắt App Hold khẩn cấp | Khóa luồng tip và gắn cờ cảnh báo trên UI | `FE_LOCAL_STATE` | `BE_DYNAMIC + CHAIN_VIA_BE` | revisionId | Cập nhật cờ hold / SUSPENDED | Ban điều hành | Ban điều hành | Khi bấm nút Hold | Thất bại kết nối | Switch state | Client action | Thời gian tối đa giữ trạng thái App Hold |\n| `/transparency` | ALL | `PublicLedger` | Sổ cái công khai số dư quỹ & nguồn thu | 45.200 USDC, 3.4 ETH; Quỹ dự án, Phí hội viên | `FE_STATIC` | `CHAIN_VIA_BE + BE_DYNAMIC` | Không | Không | Công chúng | System | Tải trang Minh bạch | Bảng rỗng | Year selector | SSG + ISR (1h) | Tần suất worker đồng bộ số dư onchain |\n| `/transparency` | ALL | `PublicLedger / Stream` | Nhật ký giao dịch mô phỏng live | Danh sách đơn thanh toán: POST_TIP, PROJECT, MEMBERSHIP | `FE_LOCAL_STATE` | `CHAIN_VIA_BE + BE_DYNAMIC` | Không | Tái dùng paymentIntentId / receiptKey | Công chúng | System | Polling 3s một lần | \"Chưa có giao dịch nào\" | Polling state | Client live query | Giới hạn số dòng hiển thị công khai (20 hay 50) |\n| `Floating` | ALL (Reviewer) | `ReviewToolbar` | Khung điều khiển nghiệm thu 14 kịch bản | 14 kịch bản, 5 personas, Bottom-left dock | `FE_LOCAL_STATE` | `FE_LOCAL_STATE` | Không | Không | Bin / QA Reviewer | Reviewer | Tải mọi trang | Thu gọn thành icon pill | Widget Open state | Client Only | Công cụ hỗ trợ Bin nghiệm thu 14 kịch bản; đặt góc dưới bên trái |\n\n---\n\n## 3. Danh sách các Quyết định Kỹ thuật Cần Bin Chốt Sau Khi Trải Nghiệm FE v1.2\n\n1. **Lưu trữ bản nháp (Draft persistence):** Hiện tại nháp phân lập lưu tại `localStorage` theo từng tab và user. Sau này có cần đồng bộ nháp lên server (`BE Draft`) khi người dùng đổi thiết bị không?\n2. **Quyền truy cập VIP Content:** Mức độ hiển thị nội dung VIP với Guest/Member thường: Làm mờ đoạn văn (blur) hay chỉ hiển thị tóm tắt và khóa toàn bộ phần nhận định chi tiết?\n3. **Cảnh báo điểm trùng lặp:** Ngưỡng khoảng cách GPS và độ tương đồng tên gọi: Khi phát hiện khả năng trùng lặp, người dùng có quyền tự quyết định tiếp tục tạo mới hay bắt buộc chuyển qua Admin duyệt?\n4. **Chi trả thù lao Chuyên gia:** Việc giải ngân từ Quỹ dự án cho các chuyên gia có công nợ `OPEN` sẽ thực hiện tự động qua Smart Contract định kỳ hàng tuần, hay Admin ký duyệt chi thủ công từng khoản?\n5. **Tiền tệ Tip & Quyên góp:** Ventlore hỗ trợ thanh toán tip và quyên góp bằng token ERC-20 (USDC) trên Arbitrum. Có cần mở rộng thêm native token (ETH) hay giải pháp thanh toán thẻ nội địa qua cổng trung gian không?\n";
